### ISSUE TITLE
Multi language support

### ISSUE THREAD

**Issue by tianchao-haohan** [elastic/packetbeat#106]
I want to make packetbeat support my native language. So I need to do the L10N task for this software.
Would you please share me that where are those resource files related to L10N.

**Comment by tsg** [comment]
Hi, there's no explicit L10N support but note that Packetbeat uses [Kibana](https://github.com/elastic/kibana) as it's UI, and almost all labels/strings in Kibana are user defined. So you can pretty easily translate the dashboards.
