### ISSUE TITLE
Fail to initialize Elasticsearch as output

### ISSUE THREAD

**Issue by schlagify** [elastic/packetbeat#107]
Hi,

I have a fresh, manual installation of elasticsearch & packetbeat, and am unable to run the packetbeat agent continuously.  It fails with the following errors

```
packetbeat -e -c /etc/packetbeat/packetbeat.conf
output_elasticsearch.go:51: ERR  Fail to set _ttl mapping: 2015-03-22 00:09:35.478772095 -0400 EDT: Error [MergeMappingException[Merge failed with failures {[mapper [_all] enabled is false now encountering true]}]] Status [400] [400]
publish.go:274: ERR  Fail to initialize Elasticsearch as output: 2015-03-22 00:09:35.478772095 -0400 EDT: Error [MergeMappingException[Merge failed with failures {[mapper [_all] enabled is false now encountering true]}]] Status [400] [400]
main.go:223: CRIT 2015-03-22 00:09:35.478772095 -0400 EDT: Error [MergeMappingException[Merge failed with failures {[mapper [_all] enabled is false now encountering true]}]] Status [400] [400]
```

On my elasticsearch box, i am seeing the following errors

```
c[2015-03-21 22:40:48,936][DEBUG][action.admin.indices.mapping.put] [Dark Beast] failed to put mappings on indices [[packetbeat-topology]], type [server-ip]
org.elasticsearch.index.mapper.MergeMappingException: Merge failed with failures {[mapper [_all] enabled is false now encountering true]}
	at org.elasticsearch.cluster.metadata.MetaDataMappingService$4.execute(MetaDataMappingService.java:511)
	at org.elasticsearch.cluster.service.InternalClusterService$UpdateTask.run(InternalClusterService.java:329)
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:153)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
```

I've applied the index template as described on http://packetbeat.com/getstarted.  

```
curl -XGET 'http://localhost:9200/_template/packetbeat?pretty'
{
  "packetbeat" : {
    "order" : 0,
    "template" : "packetbeat-*",
    "settings" : {
      "index.refresh_interval" : "1s"
    },
    "mappings" : {
      "_default_" : {
        "dynamic_templates" : [ {
          "template1" : {
            "mapping" : {
              "index" : "not_analyzed",
              "doc_values" : true,
              "type" : "{dynamic_type}"
            },
            "match" : "*"
          }
        } ],
        "date_detection" : false,
        "properties" : {
          "client_location" : {
            "type" : "geo_point"
          },
          "@timestamp" : {
            "type" : "date"
          },
          "request_raw" : {
            "index" : "analyzed",
            "type" : "string"
          },
          "response_raw" : {
            "index" : "analyzed",
            "type" : "string"
          }
        },
        "_all" : {
          "enabled" : false
        }
      }
    },
    "aliases" : { }
  }
}
```

my elasticsearch configuration:

```
egrep -vi "^$|^#" /etc/elasticsearch/elasticsearch.yml 
http.cors.allow-origin: "/.*/"
http.cors.enabled: true
```

my packetbeat configuration:

```
egrep -vi "^$|^ *#" /etc/packetbeat/packetbeat.conf 
[output]
  [output.elasticsearch]
    enabled = true
    host = "esnode01"
    port = 9200
    save_topology = true
  [output.redis]
  [output.file]
    enabled = true
    path="/var/log/packetbeat"
    filename="packetbeat.log"
[interfaces]
device = "any"
[protocols]
  [protocols.http]
  ports = [80, 9001]
  [protocols.pgsql]
  ports = [5432]
[procs]
  [procs.monitored.nginx]
  cmdline_grep = "nginx"
  [procs.monitored.app]
  cmdline_grep = "uwsgi-worker"
[agent]
tags = ["snapshots"]
[passwords]
```

Version info:

Debian Wheezy/7.8
elasticsearch 1.4.0
packetbeat 0.4.3-1
kibana-3.1.2-packetbeat

**Comment by jgrumboe** [comment]
Ich bin bis 23.03.2015 abwesend.

Ich werde Ihre Nachricht nach meiner R�ckkehr beantworten.
Ihre Nachricht wird nicht weitergeleitet.
In dringenden F�llen wenden Sie sich bitte an meine Kollegen Hr. Seidl
Matthias, Hr. Rernleitner Wolfgang oder Hr. Premec Ranko.


Hinweis: Dies ist eine automatische Antwort auf Ihre Nachricht
"[packetbeat] Fail to initialize Elasticsearch as output (#107)" gesendet
am 22.03.2015 4:15:58.

Diese ist die einzige Benachrichtigung, die Sie empfangen werden, w�hrend
diese Person abwesend ist.

**Comment by tsg** [comment]
The problem seems to be that in the getting started guide we link to the master version of the template file, not to the one related to the latest release. In this case, the template recently changed.

Can you try with this template file https://raw.githubusercontent.com/packetbeat/packetbeat/v0.4.3/packetbeat.template.json ?

**Comment by jgrumboe** [comment]
Ich bin bis 23.03.2015 abwesend.

Ich werde Ihre Nachricht nach meiner R�ckkehr beantworten.
Ihre Nachricht wird nicht weitergeleitet.
In dringenden F�llen wenden Sie sich bitte an meine Kollegen Hr. Seidl
Matthias, Hr. Rernleitner Wolfgang oder Hr. Premec Ranko.


Hinweis: Dies ist eine automatische Antwort auf Ihre Nachricht  "Re:
[packetbeat] Fail to initialize Elasticsearch as output (#107)" gesendet am
22.03.2015 19:08:41.

Diese ist die einzige Benachrichtigung, die Sie empfangen werden, w�hrend
diese Person abwesend ist.

**Comment by schlagify** [comment]
that seemed to do the trick.  thanks!   should i leave this open or anything?

**Comment by tsg** [comment]
Great, thanks. Leaving this open to fix the documentation.

**Comment by tsg** [comment]
Fixed in the meantime.
