### ISSUE TITLE
Can we change packetbeat indexed field names?

### ISSUE THREAD

**Issue by harshamadala** [elastic/packetbeat#112]
I would like to change packetbeat field names like type, as I am using other agents for other applications which has different field names. So be in sync i would like to configure field names, is it possible?

**Comment by tsg** [comment]
If you use Logstash in your pipeline, I recommend modifying the fields names with it.

**Comment by harshamadala** [comment]
I am not using logstash, I am directly pushing logs to elasticsearch from packetbeat.

**Comment by tsg** [comment]
I'm afraid we don't have this flexibility. Which fields would you want changed in particular? We are in the process of renaming some fields for the next release.

**Comment by harshamadala** [comment]
I would like to rename fields "type" and "agent", it would be nice if we have flexibility to configure these names so that we can keep some names like "service_name" and "hostname"

**Comment by whisk3y** [comment]
Out of curiosity, how would we route it through logstash? Would you use the elasticsearch input filter and just set the host? Or are you talking about writing to a log and shipping the log?

**Comment by tsg** [comment]
Currently we recommend doing this via Redis: http://packetbeat.com/blog/scaling-packetbeat-with-redis-and-logstash.html

**Comment by harshamadala** [comment]
What is advantage of adding logstash and redis in between? Have read that each agent uses less CPU and approach is scalable. Can you please elaborate?

**Comment by tsg** [comment]
The CPU is lower due to an implementation detail, the Elasticsearch output was doing inserts one by one, while the Redis output was using batching. That's actually no longer the case with `1.0.0-Beta1` because the ES output supports the bulk API.

Closing this issue as we prefer questions and discussions to go on the new [forums](https://discuss.elastic.co/c/beats/packetbeat).
