### ISSUE TITLE
Value of Affected Rows possibly incorrect in MySQL Parser

### ISSUE THREAD

**Issue by wagnerjs** [elastic/packetbeat#119]
Hi,

I think `mysqlMessageParser()` in protos/mysql/mysql.go doesnt bring correct _affected rows_ if value is greater than 250, because affected rows is _Length-Encoded Integer Type_ according to MySQL Internals: 

https://dev.mysql.com/doc/internals/en/packet-OK_Packet.html
https://dev.mysql.com/doc/internals/en/integer.html#packet-Protocol::LengthEncodedInteger

Am i right?

Regards

**Comment by monicasarbu** [comment]
Yes, you are right. I missed that. Thank you for reporting the bug. A fix will be available in the next release.

**Comment by monicasarbu** [comment]
Fixed in version 1.0.0-beta1. Closing for now.
