### ISSUE TITLE
Packet Handling

### ISSUE THREAD

**Issue by d2g** [elastic/packetbeat#12]
I can see from main.go that you are working with ipv4 packets and thought it might be worth highlighting this repository:

code.google.com/p/go.net/ipv4

http://godoc.org/code.google.com/p/go.net/ipv4

**Comment by d2g** [comment]
Not quite sure how the commits close this.

**Comment by tsg** [comment]
Yeah, sorry, I should have left a comment. The commits are not related, they are wrongly labeled due to repos merging. I closed the issue because the issue is quite old and in the meantime we switched to using the gopacket library.
