### ISSUE TITLE
Slow Query log showing negative response time

### ISSUE THREAD

**Issue by sergekh42** [elastic/packetbeat#122]
In the MySQL Performance dashboard when I go to the Slow Query Log graph and try to see the fastest queries, it shows negative numbers. Is this a bug or a configuration issue?

Picture: https://i.imgur.com/i3nrfxR.png

**Comment by tsg** [comment]
Hmm, interesting. What happens when you do a search like this?

      responsetime: [* TO 0]

Can you find documents with `resposetime < 0`. Please check in the `_source` field from the "Row" tab in Kibana.

**Comment by tsg** [comment]
Closing this one because we would need more data. In the future, we'd prefer you open questions or requests for help in an issue on the new [forums](https://discuss.elastic.co/c/beats/packetbeat) we have for Packetbeat or on the #beats channel on Freenode.
