### ISSUE TITLE
Index out of range crash

### ISSUE THREAD

**Issue by wyzbv** [elastic/packetbeat#125]
I'm using Packetbeat 5 on CentOS 6 to capture traffic from a mirror port and keep getting periodic crashes.  There doesn't seem to be any rhyme or reason as to when it crashes.

panic: runtime error: index out of range

goroutine 18 [running]:
packetbeat/protos/http.splitCookiesHeader(0xc20ac5e840, 0xa4, 0xbd6630)
        /home/vagrant/src/packetbeat/protos/http/http.go:810 +0x229
packetbeat/protos/http.(*Http).receivedHttpResponse(0xc20800a3c0, 0xc209611340)
        /home/vagrant/src/packetbeat/protos/http/http.go:736 +0xa68
packetbeat/protos/http.(*Http).handleHttp(0xc20800a3c0, 0xc209611340, 0xc20a08dc40, 0x200, 0xc209d52036, 0x2fc, 0x2fc)
        /home/vagrant/src/packetbeat/protos/http/http.go:622 +0x162
packetbeat/protos/http.(*Http).ReceivedFin(0xc20800a3c0, 0xc20a08dc40, 0xc209c4d900, 0xa52b40, 0xc208f65d80, 0x0, 0x0)
        /home/vagrant/src/packetbeat/protos/http/http.go:596 +0x2f3
packetbeat/protos/tcp.(*TcpStream).AddPacket(0xc20a08dc20, 0xc2093f0a80, 0xc209162740, 0x0)
        /home/vagrant/src/packetbeat/protos/tcp/tcp.go:83 +0x3ff
packetbeat/protos/tcp.FollowTcp(0xc209162740, 0xc2093f0a80)
        /home/vagrant/src/packetbeat/protos/tcp/tcp.go:162 +0xb47
packetbeat/protos/tcp.(*DecoderStruct).DecodePacketData(0xc209162480, 0xc209c11900, 0x36, 0x36, 0xc209712d20)
        /home/vagrant/src/packetbeat/protos/tcp/tcp.go:328 +0x47d
packetbeat/inputs/sniffer.(*SnifferSetup).Run(0xc208030730, 0x0, 0x0)
        /home/vagrant/src/packetbeat/inputs/sniffer/sniffer.go:315 +0xc35
main.func·002(0x0, 0x7f8ec4805778, 0xc208030730)
        /home/vagrant/rpmbuild/BUILD/packetbeat/main.go:243 +0x45
created by main.main
        /home/vagrant/rpmbuild/BUILD/packetbeat/main.go:249 +0x22d9

goroutine 1 [chan receive, 46 minutes]:
main.main()
        /home/vagrant/rpmbuild/BUILD/packetbeat/main.go:269 +0x264d

goroutine 17 [syscall, 46 minutes, locked to thread]:
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:2232 +0x1

goroutine 6 [syscall, 46 minutes]:
os/signal.loop()
        /usr/local/go/src/os/signal/signal_unix.go:21 +0x1f
created by os/signal.init·1
        /usr/local/go/src/os/signal/signal_unix.go:27 +0x35

goroutine 7 [select]:
github.com/bitly/go-hostpool.(*epsilonGreedyHostPool).epsilonGreedyDecay(0xc2090d6a20)
        /home/vagrant/src/github.com/bitly/go-hostpool/epsilon_greedy.go:84 +0x142
created by github.com/bitly/go-hostpool.NewEpsilonGreedy
        /home/vagrant/src/github.com/bitly/go-hostpool/epsilon_greedy.go:65 +0x3a3

goroutine 12 [chan receive]:
packetbeat/outputs.(*PublisherType).UpdateTopologyPeriodically(0x1193820)
        /home/vagrant/src/packetbeat/outputs/publish.go:166 +0x69
created by packetbeat/outputs.(*PublisherType).Init
        /home/vagrant/src/packetbeat/outputs/publish.go:299 +0x15ff

goroutine 10 [IO wait]:
net.(*pollDesc).Wait(0xc208010f40, 0x72, 0x0, 0x0)
        /usr/local/go/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc208010f40, 0x0, 0x0)
        /usr/local/go/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).Read(0xc208010ee0, 0xc209173000, 0x1000, 0x1000, 0x0, 0x7f8ec6672a20, 0xc209008788)
        /usr/local/go/src/net/fd_unix.go:242 +0x40f
net.(*conn).Read(0xc20802e9b8, 0xc209173000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/net.go:121 +0xdc
net/http.noteEOFReader.Read(0x7f8ec4807010, 0xc20802e9b8, 0xc209117a78, 0xc209173000, 0x1000, 0x1000, 0x9b33c0, 0x0, 0x0)
        /usr/local/go/src/net/http/transport.go:1270 +0x6e
net/http.(*noteEOFReader).Read(0xc209165660, 0xc209173000, 0x1000, 0x1000, 0xc208012000, 0x0, 0x0)
        <autogenerated>:125 +0xd4
bufio.(*Reader).fill(0xc20800aa20)
        /usr/local/go/src/bufio/bufio.go:97 +0x1ce
bufio.(*Reader).Peek(0xc20800aa20, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/bufio/bufio.go:132 +0xf0
net/http.(*persistConn).readLoop(0xc209117a20)
        /usr/local/go/src/net/http/transport.go:842 +0xa4
created by net/http.(*Transport).dialConn
        /usr/local/go/src/net/http/transport.go:660 +0xc9f

goroutine 11 [runnable]:
net/http.(*persistConn).writeLoop(0xc209117a20)
        /usr/local/go/src/net/http/transport.go:945 +0x41d
created by net/http.(*Transport).dialConn
        /usr/local/go/src/net/http/transport.go:661 +0xcbc

goroutine 13 [select]:
net/http.(*persistConn).roundTrip(0xc209117a20, 0xc2090087c0, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/http/transport.go:1082 +0x7ad
net/http.(*Transport).RoundTrip(0xc2090d6480, 0xc20a0deb60, 0xc209ad0180, 0x0, 0x0)
        /usr/local/go/src/net/http/transport.go:235 +0x558
net/http.send(0xc20a0deb60, 0x7f8ec48052f0, 0xc2090d6480, 0x37, 0x0, 0x0)
        /usr/local/go/src/net/http/client.go:219 +0x4fc
net/http.(*Client).send(0x1192b60, 0xc20a0deb60, 0x37, 0x0, 0x0)
        /usr/local/go/src/net/http/client.go:142 +0x15b
net/http.(*Client).doFollowingRedirects(0x1192b60, 0xc20a0deb60, 0xd2dac8, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/http/client.go:367 +0xb25
net/http.(*Client).Do(0x1192b60, 0xc20a0deb60, 0xc20a295110, 0x0, 0x0)
        /usr/local/go/src/net/http/client.go:177 +0x192
github.com/packetbeat/elastigo/api.(*Request).DoResponse(0xc20936b6e0, 0x8fab20, 0xc2097f8f58, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/vagrant/src/github.com/packetbeat/elastigo/api/request.go:163 +0x8a
github.com/packetbeat/elastigo/api.(*Request).Do(0xc20936b6e0, 0x8fab20, 0xc2097f8f58, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/vagrant/src/github.com/packetbeat/elastigo/api/request.go:155 +0x72
github.com/packetbeat/elastigo/api.DoCommand(0xb67030, 0x4, 0xc20a295050, 0x21, 0x0, 0xab96a0, 0xc209613050, 0x0, 0x0, 0x0, ...)
        /home/vagrant/src/github.com/packetbeat/elastigo/api/baseRequest.go:52 +0x2bd
github.com/packetbeat/elastigo/core.IndexWithParameters(0xc20936aa60, 0x1a, 0xb7b8f0, 0x4, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/vagrant/src/github.com/packetbeat/elastigo/core/index.go:66 +0x42d
github.com/packetbeat/elastigo/core.Index(0xc20936aa60, 0x1a, 0xb7b8f0, 0x4, 0x0, 0x0, 0x0, 0xab96a0, 0xc209613050, 0x0, ...)
        /home/vagrant/src/github.com/packetbeat/elastigo/core/index.go:44 +0x166
packetbeat/outputs.(*ElasticsearchOutputType).PublishEvent(0x1193880, 0xeccd09378, 0x621f240, 0x1192cc0, 0xc209613050, 0x0, 0x0)
        /home/vagrant/src/packetbeat/outputs/output_elasticsearch.go:149 +0x3f4
packetbeat/outputs.(*PublisherType).publishEvent(0x1193820, 0xc209613050, 0x0, 0x0)
        /home/vagrant/src/packetbeat/outputs/publish.go:151 +0x122e
packetbeat/outputs.(*PublisherType).publishFromQueue(0x1193820)
        /home/vagrant/src/packetbeat/outputs/publish.go:67 +0x89
created by packetbeat/outputs.(*PublisherType).Init
        /home/vagrant/src/packetbeat/outputs/publish.go:303 +0x165f

goroutine 14 [chan receive]:
packetbeat/procs.(*Process).RefreshPids(0xc208031270)
        /home/vagrant/src/packetbeat/procs/procs.go:132 +0xc9
created by packetbeat/procs.NewProcess
        /home/vagrant/src/packetbeat/procs/procs.go:125 +0x11d

goroutine 15 [chan receive]:
packetbeat/procs.(*Process).RefreshPids(0xc2080312c0)
        /home/vagrant/src/packetbeat/procs/procs.go:132 +0xc9
created by packetbeat/procs.NewProcess
        /home/vagrant/src/packetbeat/procs/procs.go:125 +0x11d

goroutine 16 [chan receive, 46 minutes]:
packetbeat/protos/thrift.(*Thrift).publishTransactions(0xc20802d740)
        /home/vagrant/src/packetbeat/protos/thrift/thrift.go:1006 +0x63
created by packetbeat/protos/thrift.(*Thrift).Init
        /home/vagrant/src/packetbeat/protos/thrift/thrift.go:244 +0x139

goroutine 19 [chan receive, 46 minutes]:
main.func·003()
        /home/vagrant/rpmbuild/BUILD/packetbeat/main.go:256 +0x3f
created by main.main
        /home/vagrant/rpmbuild/BUILD/packetbeat/main.go:259 +0x256f

goroutine 26 [IO wait]:
net.(*pollDesc).Wait(0xc209973870, 0x72, 0x0, 0x0)
        /usr/local/go/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc209973870, 0x0, 0x0)
        /usr/local/go/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).Read(0xc209973810, 0xc2098b6000, 0x1000, 0x1000, 0x0, 0x7f8ec6672a20, 0xc20aa08290)
        /usr/local/go/src/net/fd_unix.go:242 +0x40f
net.(*conn).Read(0xc2099425f8, 0xc2098b6000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/net.go:121 +0xdc
net/http.noteEOFReader.Read(0x7f8ec4807010, 0xc2099425f8, 0xc2094c6058, 0xc2098b6000, 0x1000, 0x1000, 0x9b33c0, 0x0, 0x0)
        /usr/local/go/src/net/http/transport.go:1270 +0x6e
net/http.(*noteEOFReader).Read(0xc2098de120, 0xc2098b6000, 0x1000, 0x1000, 0xc208012000, 0x0, 0x0)
        <autogenerated>:125 +0xd4
bufio.(*Reader).fill(0xc209314ae0)
        /usr/local/go/src/bufio/bufio.go:97 +0x1ce
bufio.(*Reader).Peek(0xc209314ae0, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/bufio/bufio.go:132 +0xf0
net/http.(*persistConn).readLoop(0xc2094c6000)
        /usr/local/go/src/net/http/transport.go:842 +0xa4
created by net/http.(*Transport).dialConn
        /usr/local/go/src/net/http/transport.go:660 +0xc9f

goroutine 27 [select]:
net/http.(*persistConn).writeLoop(0xc2094c6000)
        /usr/local/go/src/net/http/transport.go:945 +0x41d
created by net/http.(*Transport).dialConn
        /usr/local/go/src/net/http/transport.go:661 +0xcbc

What else would be helpful to troubleshoot?

**Comment by tsg** [comment]
Thanks for the report, we'll have a look asap.

**Comment by rswart** [comment]
I had the same error on a Set-Cookie header ending with a semi-colon when split headers is enabled:

`Set-Cookie: cookiename=value;path=/;domain=.xxx.com;`

Above pull requests fixes this.



Above pull request fixes this for me.

**Comment by rswart** [comment]
Thinking about this a little more, the pull request is not sufficient to handle all edge cases. Cookie values can be surrounded by double quotes and contain special characters used in the split functions (equals sign & semi-colon).

**Comment by tsg** [comment]
Thanks @rswart, I also had a work in progress patch for this issue. I'll check your pull request and push it in a few days.

**Comment by tsg** [comment]
We fixed this in the meantime, see this commit: https://github.com/elastic/packetbeat/commit/e30004cfd4e56af18955bd5c611fa010cef66331
