### ISSUE TITLE
Running PacketBeat Agent on each Kubernetes Pod

### ISSUE THREAD

**Issue by mingfang** [elastic/packetbeat#133]
I'm currently running the PacketBeat Agent each host that is also a Kubernetes Node using --net=host.
Here is my Agent https://github.com/mingfang/docker-packetbeat-agent

This works but I loose the ability to identify the flow for each Pod; Every Rest call on each host comes from the same Agent.  
To fix it I was thinking about running an Agent on each Pod.
Question is, is this inefficient?
I can imagine this will require more memory since I'll be running multiple Agents, but they should use the same CPU since all in all they are decoding the same number of packets.

It would be great if there is a way to run one Agent at the host level and still be able to somehow identify each packet from each Docker container. hint hint.

**Comment by tsg** [comment]
Sorry for the late answer. There is some overhead in memory, but CPU wise I think there shouldn't be too much of a difference, unless the agents see some of the traffic twice. Closing the issue as from now on we prefer questions on the new [forums](https://discuss.elastic.co/c/beats/packetbeat).
