### ISSUE TITLE
Protocols Roadmap?

### ISSUE THREAD

**Issue by stephanbuys** [elastic/packetbeat#142]
Hi,

Is there a document somewhere (or any information) that highlights the protocol roadmap? We'd like to contribute but don't want to invest time in decoding protocols thats already being developed for internally at Elastic?

**Comment by tsg** [comment]
Hi Stephan, we didn't yet have the time to set the protocol roadmap. We'll share it as soon as we have a clear idea. Which protocols would you be interested in?

**Comment by stephanbuys** [comment]
@tsg some of the ones we'd be interested in would be DNS, TCP Flows, MSSQL, CIFS/SMB (and later https)

**Comment by tsg** [comment]
Thanks, recorded. We'll work on the roadmap and announce it as soon as we can.

**Comment by darxriggs** [comment]
Hi, is there any progress on the roadmap?

I would also be interested in a planned release date for PacketBeat 1.0.0 GA.

**Comment by tsg** [comment]
Current target dates are Oct 19th for beta4 which will mainly mean the release of Filebeat and then making all the the Beats GA Nov 2nd. Target dates, especially the GA one, are of course subject to change in case we find serious issues.
