### ISSUE TITLE
Packetbeat and Kibana4

### ISSUE THREAD

**Issue by cello86** [elastic/packetbeat#165]
Hi All,
I tried to install Packetbeat with Elasticsearch 1.6.0 and Kibana 4.1.0. I configured the agent to collect MySQL traffic end push directly the data to a standalone server and all works fine. I downloaded the dashboards and loaded them to Elasticsearch, but the dashboard reports error on "@timestamp" field missing on the indices data.

I checked and the field is missing. Is it a packetbeat configuration problem?

Thanks in advance,
Marcello

**Comment by tsg** [comment]
The latest version of the `packetbeat-dashboards` should only use the `timestamp` field, not the `@timestamp` field. Did you downloaded them from this URL: `https://download.elastic.co/beats/packetbeat/packetbeat-dashboards-1.0.0~Beta1.tar.gz` ?

When configuring in Kibana4, did it offer the choice between `@timestamp` and `timestamp` fields?

**Comment by tsg** [comment]
Another question, did you upgrade from a previous version of packetbeat or dashboards? Or is this a fresh new installation?

**Comment by cello86** [comment]
This is a fresh installation and I downloaded the dashboard from the github repo. When I configured the packetbeat-* index I have specified the timestamp field

**Comment by tsg** [comment]
Downloaded from here https://github.com/elastic/packetbeat-dashboards/releases ? Or cloned the repo?

In any case, that also refers only to `timestamp` and not `@timestamp`, so I'm confused. 

What about the template, can you check that:

    curl 'http://<<es_url>>/_template/packetbeat?pretty'

defines `timestamp` and not `@timestamp`?

**Comment by cello86** [comment]
I downloaded the dashboards from https://github.com/elastic/packetbeat-dashboards/archive/master.zip.

The error reported is ony for the @timestamp field not present.

The template imported is:

{
  "packetbeat" : {
    "order" : 0,
    "template" : "packetbeat-*",
    "settings" : {
      "index.refresh_interval" : "5s"
    },
    "mappings" : {
      "_default_" : {
        "dynamic_templates" : [ {
          "template1" : {
            "mapping" : {
              "index" : "not_analyzed",
              "ignore_above" : 1024,
              "doc_values" : true,
              "type" : "{dynamic_type}"
            },
            "match" : "*"
          }
        } ],
        "properties" : {
          "timestamp" : {
            "type" : "date"
          },
          "response" : {
            "index" : "analyzed",
            "norms" : {
              "enabled" : false
            },
            "type" : "string"
          },
          "client_location" : {
            "type" : "geo_point"
          },
          "query" : {
            "index" : "not_analyzed",
            "doc_values" : true,
            "type" : "string"
          },
          "request" : {
            "index" : "analyzed",
            "norms" : {
              "enabled" : false
            },
            "type" : "string"
          },
          "params" : {
            "index" : "analyzed",
            "norms" : {
              "enabled" : false
            },
            "type" : "string"
          }
        },
        "_all" : {
          "enabled" : true,
          "norms" : {
            "enabled" : false
          }
        }
      }
    },
    "aliases" : { }
  }
}

**Comment by tsg** [comment]
Hmm, the template looks fine and the dashboards don't contain `@timestamp` anywhere. You can check yourself with grep. What exactly is the Kibana error? Can you post a screenshot?

**Comment by cello86** [comment]
Hi,
I downloaded the https://github.com/elastic/packetbeat-dashboards/releases version and the timestamp is matched correctly. The only remained issue is related to the field bytes_in as you can see on the image.

marcello
![kibana](https://cloud.githubusercontent.com/assets/6987539/8181278/f4024acc-1424-11e5-8705-0107b7322e3f.png)

**Comment by tsg** [comment]
Ok, glad the '@timestamp' issue is solved. Indeed it seems the beta1 doesn't include the `bytes_in` for mysql. I posted #167 to fix this, thanks for reporting.
