### ISSUE TITLE
Add bytes_in and bytes_out field to all protocols

### ISSUE THREAD

**Issue by tsg** [elastic/packetbeat#167]
The `bytes_in` and `bytes_out` fields are supported in some protocols but not in all of them. Their definition is:

* `bytes_in` - the size in bytes of the request
* `bytes_out` - the size in bytes of the response

They make sense for all the currently supported protocols, so we should implement them for all.

**Comment by monicasarbu** [comment]
Currently, it is implemented only for Redis and Thrift rpc.

**Comment by monicasarbu** [comment]
For MySQL: https://github.com/elastic/packetbeat/commit/6f9b26969a28a69f7d667f2d2850a6c93712ecfc
