### ISSUE TITLE
packetbeat process hangs on a busy mysql box

### ISSUE THREAD

**Issue by spolk01** [elastic/packetbeat#168]
v0.5.0-1

On a very busy mysql server (tens of thousands of sql ops per sec at peaks), packetbeat process appears to stop shipping data to elasticsearch. It initially works fine for number of hours only to stop eventually.

When this happens packetbeat process appears to be hung - it is still active as in taking up CPU time but it is not shipping data to ES instance. Also it refuses to die when issued TERM signal (KILL does the job). Nothing is logged in the log.

I have the same version deployed on the whole stack, there are three mysql servers in the cluster. This problem only occurs on the active instance of the DB (the other two just replicate) - less busy servers as well PB instances running on other type of servers (http, etc) do continue to work just fine.

**Comment by tsg** [comment]
Hi, thanks for reporting. It would be great if you could start it in foreground on the machine where this happens, with something like this (for 0.5.0):

    packetbeat -c /etc/packetbeat/packetbeat.conf

And after it hangs, kill it with SIGQUIT, something like this:

    sudo kill -QUIT <pid>

This should print a stacktrace which will hopefully help us identify the issue.

**Comment by spolk01** [comment]
SIGQUIT: quit
PC=0x4484b1

goroutine 6 [syscall, 1472 minutes]:
runtime.notetsleepg(0x16caac0, 0xffffffffffffffff, 0xb93901)
	/usr/local/go/src/runtime/lock_futex.go:201 +0x52 fp=0xc20801d768 sp=0xc20801d740
runtime.signal_recv(0x172)
	/usr/local/go/src/runtime/sigqueue.go:109 +0x135 fp=0xc20801d7a0 sp=0xc20801d768
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:21 +0x1f fp=0xc20801d7e0 sp=0xc20801d7a0
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2232 +0x1 fp=0xc20801d7e8 sp=0xc20801d7e0
created by os/signal.init·1
	/usr/local/go/src/os/signal/signal_unix.go:27 +0x35

goroutine 1 [chan receive, 1472 minutes]:
main.main()
	/home/vagrant/rpmbuild/BUILD/packetbeat/main.go:269 +0x264d

goroutine 17 [syscall, 1472 minutes, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2232 +0x1

goroutine 7 [select]:
github.com/bitly/go-hostpool.(*epsilonGreedyHostPool).epsilonGreedyDecay(0xc2090d8b40)
	/home/vagrant/src/github.com/bitly/go-hostpool/epsilon_greedy.go:84 +0x142
created by github.com/bitly/go-hostpool.NewEpsilonGreedy
	/home/vagrant/src/github.com/bitly/go-hostpool/epsilon_greedy.go:65 +0x3a3

goroutine 12 [chan receive]:
packetbeat/outputs.(*PublisherType).UpdateTopologyPeriodically(0x1193820)
	/home/vagrant/src/packetbeat/outputs/publish.go:166 +0x69
created by packetbeat/outputs.(*PublisherType).Init
	/home/vagrant/src/packetbeat/outputs/publish.go:299 +0x15ff

goroutine 10 [IO wait]:
net.(*pollDesc).Wait(0xc2080112c0, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc2080112c0, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).Read(0xc208011260, 0xc209178000, 0x1000, 0x1000, 0x0, 0x7f945edffa20, 0xc208f3ee40)
	/usr/local/go/src/net/fd_unix.go:242 +0x40f
net.(*conn).Read(0xc20802ec00, 0xc209178000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:121 +0xdc
net/http.noteEOFReader.Read(0x7f945cf933d0, 0xc20802ec00, 0xc209119918, 0xc209178000, 0x1000, 0x1000, 0x9b33c0, 0x0, 0x0)
	/usr/local/go/src/net/http/transport.go:1270 +0x6e
net/http.(*noteEOFReader).Read(0xc20915d280, 0xc209178000, 0x1000, 0x1000, 0xc208012000, 0x0, 0x0)
	<autogenerated>:125 +0xd4
bufio.(*Reader).fill(0xc208032cc0)
	/usr/local/go/src/bufio/bufio.go:97 +0x1ce
bufio.(*Reader).Peek(0xc208032cc0, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/bufio/bufio.go:132 +0xf0
net/http.(*persistConn).readLoop(0xc2091198c0)
	/usr/local/go/src/net/http/transport.go:842 +0xa4
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:660 +0xc9f

goroutine 11 [select]:
net/http.(*persistConn).writeLoop(0xc2091198c0)
	/usr/local/go/src/net/http/transport.go:945 +0x41d
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:661 +0xcbc

goroutine 13 [chan receive, 1448 minutes]:
packetbeat/outputs.(*PublisherType).publishFromQueue(0x1193820)
	/home/vagrant/src/packetbeat/outputs/publish.go:66 +0x5e
created by packetbeat/outputs.(*PublisherType).Init
	/home/vagrant/src/packetbeat/outputs/publish.go:303 +0x165f

goroutine 14 [chan receive]:
packetbeat/procs.(*Process).RefreshPids(0xc208031680)
	/home/vagrant/src/packetbeat/procs/procs.go:132 +0xc9
created by packetbeat/procs.NewProcess
	/home/vagrant/src/packetbeat/procs/procs.go:125 +0x11d

goroutine 15 [chan receive, 1472 minutes]:
packetbeat/protos/thrift.(*Thrift).publishTransactions(0xc20802d740)
	/home/vagrant/src/packetbeat/protos/thrift/thrift.go:1006 +0x63
created by packetbeat/protos/thrift.(*Thrift).Init
	/home/vagrant/src/packetbeat/protos/thrift/thrift.go:244 +0x139

goroutine 16 [running]:
	goroutine running on other thread; stack unavailable
created by main.main
	/home/vagrant/rpmbuild/BUILD/packetbeat/main.go:249 +0x22d9

goroutine 18 [chan receive, 1472 minutes]:
main.func·003()
	/home/vagrant/rpmbuild/BUILD/packetbeat/main.go:256 +0x3f
created by main.main
	/home/vagrant/rpmbuild/BUILD/packetbeat/main.go:259 +0x256f

goroutine 25 [IO wait, 1449 minutes]:
net.(*pollDesc).Wait(0xc209dbb100, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc209dbb100, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).Read(0xc209dbb0a0, 0xc209e78000, 0x1000, 0x1000, 0x0, 0x7f945edffa20, 0xc20a5fef48)
	/usr/local/go/src/net/fd_unix.go:242 +0x40f
net.(*conn).Read(0xc20a221ad8, 0xc209e78000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:121 +0xdc
net/http.noteEOFReader.Read(0x7f945cf933d0, 0xc20a221ad8, 0xc20a053de8, 0xc209e78000, 0x1000, 0x1000, 0x9b33c0, 0x0, 0x0)
	/usr/local/go/src/net/http/transport.go:1270 +0x6e
net/http.(*noteEOFReader).Read(0xc209ee13a0, 0xc209e78000, 0x1000, 0x1000, 0xc208012000, 0x0, 0x0)
	<autogenerated>:125 +0xd4
bufio.(*Reader).fill(0xc2098034a0)
	/usr/local/go/src/bufio/bufio.go:97 +0x1ce
bufio.(*Reader).Peek(0xc2098034a0, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/bufio/bufio.go:132 +0xf0
net/http.(*persistConn).readLoop(0xc20a053d90)
	/usr/local/go/src/net/http/transport.go:842 +0xa4
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:660 +0xc9f

goroutine 26 [select, 1449 minutes]:
net/http.(*persistConn).writeLoop(0xc20a053d90)
	/usr/local/go/src/net/http/transport.go:945 +0x41d
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:661 +0xcbc

rax     0xca
rbx     0x16caac0
rcx     0xffffffffffffffff
rdx     0x0
rdi     0x16caac0
rsi     0x0
rbp     0x1
rsp     0xc20801d6c0
r8      0x0
r9      0x0
r10     0x0
r11     0x286
r12     0x1192cc0
r13     0x3397cf2f
r14     0xecd1365e9
r15     0x10
rip     0x4484b1
rflags  0x286
cs      0x33
fs      0x0
gs      0x0

**Comment by tsg** [comment]
<pre>
goroutine 16 [running]:
    goroutine running on other thread; stack unavailable
</pre>

Damn, that's not very useful. It might be (the not useful stacktrace) because of this issue: https://github.com/golang/go/issues/10546 

If that is the case, a workaround would be to run with GOMAXPROCS set to 2, something like this:

      GOMAXPROCS=2 packetbeat -c /etc/packetbeat/packetbeat.conf

And then do SIGQUIT again. I don't like it to much because it means we vary another important setting, but I think it's the easiest way to get more hints for now.

**Comment by tsg** [comment]
@spolk01 did you had the chance to try the above? Or did things evolve in any way?

**Comment by spolk01** [comment]
Sorry for the delay. It does not always day with any useful output to be shared, but here it is.

SIGQUIT: quit
PC=0x4484b1

goroutine 0 [idle]:
runtime.futex(0x11941b8, 0x0, 0x0, 0x0, 0x0, 0x1193020, 0x1, 0x41604f, 0x41626e, 0x11941b8, ...)
	/usr/local/go/src/runtime/sys_linux_amd64.s:277 +0x21
runtime.futexsleep(0x11941b8, 0x0, 0xffffffffffffffff)
	/usr/local/go/src/runtime/os_linux.c:49 +0x47
runtime.notesleep(0x11941b8)
	/usr/local/go/src/runtime/lock_futex.go:145 +0xae
stopm()
	/usr/local/go/src/runtime/proc.c:1178 +0x119
findrunnable(0xc208012900)
	/usr/local/go/src/runtime/proc.c:1487 +0x562
schedule()
	/usr/local/go/src/runtime/proc.c:1575 +0x151
runtime.park_m(0xc2091b4480)
	/usr/local/go/src/runtime/proc.c:1654 +0x113
runtime.mcall(0x43eb94)
	/usr/local/go/src/runtime/asm_amd64.s:186 +0x5a

goroutine 1 [chan receive, 10175 minutes]:
main.main()
	/home/vagrant/rpmbuild/BUILD/packetbeat/main.go:269 +0x264d

goroutine 17 [syscall, 10175 minutes, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2232 +0x1

goroutine 19 [syscall, 10175 minutes]:
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:21 +0x1f
created by os/signal.init·1
	/usr/local/go/src/os/signal/signal_unix.go:27 +0x35

goroutine 20 [select]:
github.com/bitly/go-hostpool.(*epsilonGreedyHostPool).epsilonGreedyDecay(0xc2090f6b40)
	/home/vagrant/src/github.com/bitly/go-hostpool/epsilon_greedy.go:84 +0x142
created by github.com/bitly/go-hostpool.NewEpsilonGreedy
	/home/vagrant/src/github.com/bitly/go-hostpool/epsilon_greedy.go:65 +0x3a3

goroutine 8 [chan receive]:
packetbeat/outputs.(*PublisherType).UpdateTopologyPeriodically(0x1193820)
	/home/vagrant/src/packetbeat/outputs/publish.go:166 +0x69
created by packetbeat/outputs.(*PublisherType).Init
	/home/vagrant/src/packetbeat/outputs/publish.go:299 +0x15ff

goroutine 6 [IO wait, 8816 minutes]:
net.(*pollDesc).Wait(0xc2091b0060, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc2091b0060, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).Read(0xc2091b0000, 0xc2091b2000, 0x1000, 0x1000, 0x0, 0x7fc232dd8a20, 0xc208f35f08)
	/usr/local/go/src/net/fd_unix.go:242 +0x40f
net.(*conn).Read(0xc20804c338, 0xc2091b2000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:121 +0xdc
net/http.noteEOFReader.Read(0x7fc230589218, 0xc20804c338, 0xc2091ae058, 0xc2091b2000, 0x1000, 0x1000, 0x9b33c0, 0x0, 0x0)
	/usr/local/go/src/net/http/transport.go:1270 +0x6e
net/http.(*noteEOFReader).Read(0xc209172180, 0xc2091b2000, 0x1000, 0x1000, 0xc208012900, 0x0, 0x0)
	<autogenerated>:125 +0xd4
bufio.(*Reader).fill(0xc2091a2240)
	/usr/local/go/src/bufio/bufio.go:97 +0x1ce
bufio.(*Reader).Peek(0xc2091a2240, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/bufio/bufio.go:132 +0xf0
net/http.(*persistConn).readLoop(0xc2091ae000)
	/usr/local/go/src/net/http/transport.go:842 +0xa4
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:660 +0xc9f

goroutine 7 [select, 8816 minutes]:
net/http.(*persistConn).writeLoop(0xc2091ae000)
	/usr/local/go/src/net/http/transport.go:945 +0x41d
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:661 +0xcbc

goroutine 9 [chan receive, 8816 minutes]:
packetbeat/outputs.(*PublisherType).publishFromQueue(0x1193820)
	/home/vagrant/src/packetbeat/outputs/publish.go:66 +0x5e
created by packetbeat/outputs.(*PublisherType).Init
	/home/vagrant/src/packetbeat/outputs/publish.go:303 +0x165f

goroutine 10 [chan receive]:
packetbeat/procs.(*Process).RefreshPids(0xc209170690)
	/home/vagrant/src/packetbeat/procs/procs.go:132 +0xc9
created by packetbeat/procs.NewProcess
	/home/vagrant/src/packetbeat/procs/procs.go:125 +0x11d

goroutine 11 [chan receive, 10175 minutes]:
packetbeat/protos/thrift.(*Thrift).publishTransactions(0xc20805d5c0)
	/home/vagrant/src/packetbeat/protos/thrift/thrift.go:1006 +0x63
created by packetbeat/protos/thrift.(*Thrift).Init
	/home/vagrant/src/packetbeat/protos/thrift/thrift.go:244 +0x139

goroutine 12 [runnable]:
packetbeat/protos/mysql.read_lstring(0xc2095fde04, 0x16f, 0x16f, 0x138, 0xc2095fdf3c, 0x0, 0x37, 0x138, 0x416001, 0x0, ...)
	/home/vagrant/src/packetbeat/protos/mysql/mysql.go:727
packetbeat/protos/mysql.(*Mysql).parseMysqlResponse(0xc2090efe60, 0xc2095fde04, 0x16f, 0x16f, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/vagrant/src/packetbeat/protos/mysql/mysql.go:662 +0x72a
packetbeat/protos/mysql.(*Mysql).receivedMysqlResponse(0xc2090efe60, 0xc209404780)
	/home/vagrant/src/packetbeat/protos/mysql/mysql.go:552 +0x728
packetbeat/protos/mysql.handleMysql(0xc2090efe60, 0xc209404780, 0xc209f37740, 0xc2092bb300, 0xc2095fde04, 0x16f, 0x16f)
	/home/vagrant/src/packetbeat/protos/mysql/mysql.go:461 +0x165
packetbeat/protos/mysql.(*Mysql).Parse(0xc2090efe60, 0xc20a504b40, 0xc209f37740, 0xc20802fe00, 0xa52c00, 0xc208ba7a40, 0x0, 0x0)
	/home/vagrant/src/packetbeat/protos/mysql/mysql.go:422 +0x4ff
packetbeat/protos/tcp.(*TcpStream).AddPacket(0xc209f37720, 0xc20a504b40, 0xc2091ee2c0, 0x0)
	/home/vagrant/src/packetbeat/protos/tcp/tcp.go:79 +0x341
packetbeat/protos/tcp.FollowTcp(0xc2091ee2c0, 0xc20a504b40)
	/home/vagrant/src/packetbeat/protos/tcp/tcp.go:162 +0xb47
packetbeat/protos/tcp.(*DecoderStruct).DecodePacketData(0xc2091ee000, 0xc2095fddc0, 0x1b3, 0x1b3, 0xc20947df80)
	/home/vagrant/src/packetbeat/protos/tcp/tcp.go:328 +0x47d
packetbeat/inputs/sniffer.(*SnifferSetup).Run(0xc20804e690, 0x0, 0x0)
	/home/vagrant/src/packetbeat/inputs/sniffer/sniffer.go:315 +0xc35
main.func·002(0x0, 0x7fc230587858, 0xc20804e690)
	/home/vagrant/rpmbuild/BUILD/packetbeat/main.go:243 +0x45
created by main.main
	/home/vagrant/rpmbuild/BUILD/packetbeat/main.go:249 +0x22d9

goroutine 13 [chan receive, 10175 minutes]:
main.func·003()
	/home/vagrant/rpmbuild/BUILD/packetbeat/main.go:256 +0x3f
created by main.main
	/home/vagrant/rpmbuild/BUILD/packetbeat/main.go:259 +0x256f

goroutine 34 [select]:
net/http.(*persistConn).writeLoop(0xc209443810)
	/usr/local/go/src/net/http/transport.go:945 +0x41d
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:661 +0xcbc

goroutine 16 [IO wait]:
net.(*pollDesc).Wait(0xc20a0c2fb0, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc20a0c2fb0, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).Read(0xc20a0c2f50, 0xc2095de000, 0x1000, 0x1000, 0x0, 0x7fc232dd8a20, 0xc208f3d800)
	/usr/local/go/src/net/fd_unix.go:242 +0x40f
net.(*conn).Read(0xc209a70930, 0xc2095de000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:121 +0xdc
net/http.noteEOFReader.Read(0x7fc230589218, 0xc209a70930, 0xc209443868, 0xc2095de000, 0x1000, 0x1000, 0x9b33c0, 0x0, 0x0)
	/usr/local/go/src/net/http/transport.go:1270 +0x6e
net/http.(*noteEOFReader).Read(0xc2095dc0c0, 0xc2095de000, 0x1000, 0x1000, 0xc208012900, 0x0, 0x0)
	<autogenerated>:125 +0xd4
bufio.(*Reader).fill(0xc20a0f43c0)
	/usr/local/go/src/bufio/bufio.go:97 +0x1ce
bufio.(*Reader).Peek(0xc20a0f43c0, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/bufio/bufio.go:132 +0xf0
net/http.(*persistConn).readLoop(0xc209443810)
	/usr/local/go/src/net/http/transport.go:842 +0xa4
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:660 +0xc9f

rax     0xca
rbx     0x11941b8
rcx     0xffffffffffffffff
rdx     0x0
rdi     0x11941b8
rsi     0x0
rbp     0x1
rsp     0x7fffec0f5be8
r8      0x0
r9      0x0
r10     0x0
r11     0x286
r12     0x6
r13     0xa
r14     0xecd2495ae
r15     0x18
rip     0x4484b1
rflags  0x286
cs      0x33
fs      0x0
gs      0x0

**Comment by tsg** [comment]
This looks better, many thanks. Looks like it's spinning in that mysql code. What's the CPU usage while it happens? Does it go to 100%?

**Comment by spolk01** [comment]
yup 100% CPU use pretty much the case

**Comment by tsg** [comment]
I expect the above commit to fix this. Thanks again for the trace!
