### ISSUE TITLE
Where is the body in HTTP proto ?

### ISSUE THREAD

**Issue by athoune** [elastic/packetbeat#172]
Previous version of packetbeat sends body in request and response, so, it was possible to watch REST services. Now, with the YAML version, only headers can be sent.

I'm working on a REST black box debugger/analyzer : https://github.com/bearstech/packetbeat.py and it only works with old packetbeat.

The code is still here for building body from packets, but the option vanished.
Do you need a pull request to activate body in proto?

**Comment by tsg** [comment]
You need to configure it to include the body of the message like this:

<pre>
protocols:
  http:
    ports: [80, 8080]
    send_response: true
    include_body_for: ["application/json"]
</pre>

The body will be present in the "response" field, which will contain the headers as well. Do you need the body as an individual field? That we don't have in the current version, I'm not sure if we had it before and was lost during refactoring.

**Comment by athoune** [comment]
The request and response fields are enough.
