### ISSUE TITLE
Windows Doc is incorrect

### ISSUE THREAD

**Issue by shadowcodex** [elastic/packetbeat#177]
The windows doc shows how to get to a windows package, and install it. However the site does not show win32 or 64 anymore...

Halp?!?!!

https://github.com/elastic/packetbeat/blob/master/docs/windows.asciidoc

**Comment by tsg** [comment]
We left the windows docs in the source code but they are not included in the index so we consider them "not published". We should have windows packaging back relatively soon (think sometime in August), we just want to have the build process and testing for them properly automated. We also want to have a better experience under windows, for example the old version required a 3rd party service wrapper.

This is the ticket: #163.
