### ISSUE TITLE
Manually compiled packetbeat doesn't stop gracefully

### ISSUE THREAD

**Issue by falzm** [elastic/packetbeat#190]
When running a packetbeat process compiled from master branch, it doesn't exit when receiving a INT (such as control-c when running in foreground) or TERM signal: I'm only able to stop the process by KILLing it. This does not occur when running the latest stable binary release from https://elastic.co.

I'm running Packetbeat on a Linux 64 bits, compiled with Go 1.4.2. Let me know if you need me to provide more information.

**Comment by tsg** [comment]
Just committed this today: https://github.com/elastic/packetbeat/commit/bc9c2f1f09bf16dbd9c3f89c87245ba35dc17e1c

Can you try updating and trying again?

**Comment by falzm** [comment]
That makes the trick, thanks!
