### ISSUE TITLE
Install fail - RPM unable to find checkcfg on an openSUSE

### ISSUE THREAD

**Issue by putztzu** [elastic/packetbeat#209]
Ordinarily the elastic family RPMs should install fine on openSUSE if they are written generically. On an openSUSE 13.2 system, install fails because unable to find checkcfg although is installed.

Typically this kind of problem is caused by specifying a fixed path instead of a relative path to find the library/dependency.

**Comment by tsg** [comment]
Thanks for the report, we'll have a new packaging system for beta3, which is based on FPM, so this will hopefully work. I'll try to have opensuse in our list of platforms we test against.

**Comment by putztzu** [comment]
Might I suggest using the Open Build Service
http://openbuildservice.org/

Using the OBS, from a common source, you can typically build any package for all the target platforms you'd ever likely want to support. With some simple clicks, you can choose to build packages that target distros for all major distros and even distro versions automatically that use DEB and RPM (at least).

This becomes even more important when it will come to building packages for future versions, minimizing changes to your codebase moving forward.

**Comment by putztzu** [comment]
This error seems to be fixed in Beta3 and can be closed.
