### ISSUE TITLE
Compile fail - gap between $GOPATH and the cloned repo

### ISSUE THREAD

**Issue by putztzu** [elastic/packetbeat#210]
main.go:18:2: cannot find package "github.com/elastic/packetbeat/config" in any of:

reported immediately when starting the build. the above described path results when the folders are not created exactly as described in the following 
https://github.com/elastic/packetbeat/blob/master/CONTRIBUTING.md

In order to conform with my other build environments, I specified a different path appending to the $GOPATH. For now, I will change to accomodate this error, but IMO this error should be avoided by either specifying the $GOPATH to extend to the root of cloned repository or modify how the code executes.

**Comment by tsg** [comment]
I don't like having to clone in the GOPATH, but I'm not sure we have a cleaner solution. Messing with the GOPATH is equally ugly. You can clone it there (or do `go get github.com/elastic/packetbeat`) and then symlink it to your preferred location.

**Comment by putztzu** [comment]
Looking at my original post I think I was probably unclear.
The issue I was complaining about is really that part of the path is hardcoded into your existing build config instead of keeping the path completely separate from what happens within the cloned repo.

My concrete recommendation:
1. "/src/github.com/elastic/packetbeat/" should be removed from the command that invokes the config file.
2. The GOPATH should describe the entire path to the root of the cloned repo and not just to $HOME as described in existing documentation, resulting in a cloned repo that can be placed anywhere. For the current guide which creates the directories ~/github.com/elastic/ the revised documentation would then read to create a path not just to $HOME but to

$HOME/src//github.com/elastic/packetbeat
