### ISSUE TITLE
Compiled without error - But where is the result?

### ISSUE THREAD

**Issue by putztzu** [elastic/packetbeat#211]
Because am having problems with existing pre-compiled binaries, am attempting to compile on machine following the instructions at
https://github.com/elastic/packetbeat/blob/master/CONTRIBUTING.md

Compile completed without error, but when I inspect the packetbeat repo root, I don't see a new file. I am used to looking for a result in a /bin directory or the root nothing new can be found. Because this is on an RPM based machine (openSUSE 13.2), I've also looked in the rpm folder but still there is no binary or package.

**Comment by tsg** [comment]
After running `make` you should see `packetbeat` in the root directory of the repository. Is it not the case?

**Comment by putztzu** [comment]
Yes, I see that.
Hmmm...  Wonder how I missed that.
I don't know if I'm just unusual for not noticing, but many projects output to a /bin folder for generated binaries.

Thx.

**Comment by putztzu** [comment]
Additional Question:
I'm guessing, but is a packetbeat binary cross-platform/cross-distro? Once compiled, can it be copied to any machine running a same type OS (like Linux) (with the required packetbeat.yml) and run?

Thx.

**Comment by andrewkroh** [comment]
The linux packetbeat binaries that we release using [beats-packer](https://github.com/elastic/beats-packer) should work on any distribution that has a glibc version newer than 2.11 (released in 2009). Libpcap is statically linked so you don't even need to have a libpcap installed.
