### ISSUE TITLE
Negative MongoDB responsetime

### ISSUE THREAD

**Issue by augustin149** [elastic/packetbeat#216]
I install the packetbeat-1.0.0-beta2-x86_64.rpm in my MongoDB instance. I notice the negative response time in the kibana.
![662636bf2c1d6b2e04c944a2ae6c8536c57d55f3](https://cloud.githubusercontent.com/assets/3971893/9596796/c9e6973e-5047-11e5-990c-1df248ca6ecd.jpg)

We build mongodb replica set with three instances, all the three instances have packetbeat installed. Please investigate this issue, let me know if you need more information.

**Comment by ruflin** [comment]
@augustin149 You mention in https://discuss.elastic.co/t/negative-mongodb-responsetime/28157 that you use a replica set. Can you give some more details on your setup?

**Comment by ruflin** [comment]
A potentially related issue https://github.com/elastic/packetbeat/issues/122

**Comment by augustin149** [comment]
The mongodb replica set is set up with three instances, one instance as the primary node that receives the read/write operations, two instances as the secondary nodes that replicate the primary’s oplog and apply the operations to their data sets.

I install the packetbeat all three nodes, I attach the packetbeat.yml print screen here.
![packetbeat_yml](https://cloud.githubusercontent.com/assets/3971893/9621410/dc23ea6c-50f3-11e5-87b1-ce14d391500d.jpg)

Please feel free to let me know if you need more information.

**Comment by ruflin** [comment]
@augustin149 Thanks for providing more data. We discussed the problem internally and it could be that packetbeat somehow mixes up some packages so request and response are not mapped correctly. This is only a theory so far.

Our assumption is that this could happen under heavy load or for queries which take very long. Heavy load could be cause through the replicas. Do you know if you also see the "replica" traffic in your kibana? Do you see any patterns in the entries with a negative responsetime? One pattern that I see is that the response times are almost too similar.

Best for us to debug the issue would be some pcap file analyse and test it. These files can be generated through running packetbeat with the option `-dump file`. Would it possible for you make such a file available to us? If there is information that should not shared publicly you can also reach me via e-mail.

**Comment by andrewkroh** [comment]
I will add another theory...

I briefly looked at the mongodb code. It appears that the code drops responses that are received without a request meaning no response can arrive before a request. This _should_ make it impossible to have a negative response time even if packetbeat is not correctly correlating requests and responses, assuming the system clock is monotonically increasing.

For AF_PACKET, the time stamps contained in the packets are generated when the device driver hands the packet to the kernel. So if you were seeing this issue periodically (not for all packets) then possibly there is an issue with the system clock. (I have seen clock issues with VMs where the hypervisor clock synchronization conflicts with NTP causing periodic multi-second clock corrections to occur.)

Questions for @augustin149:
* Are you seeing negative response times for all of the transactions?
* Are you seeing this issue in data produced by all three instances of packetbeat?
* Are there any issues with the system's clock? Can you check /var/log/messages for issues related to ntpd/time/clock?
* Like @ruflin said, a pcap would be very helpful for debugging.

**Comment by ruflin** [comment]
@andrewkroh Good point. @urso Also mentioned something similar with time jumps. This would also explain why most of the responsetimes are almost identical.

**Comment by urso** [comment]
@augustin149  you using ntp/ptp? Which client are you using? Can you check the logs for some time drift and some clock adjustments? Virtual machines are prone to worsen the timing effect, but these kind of issue also happen on physical machines.

Also, the system clock use to set packet timestamps is not fully monotonic. If packets are received very very close in time the computed response time might not be reliable.

**Comment by augustin149** [comment]
@andrewkroh @urso @ruflin Sorry for the late response, I am out for several days.

Here are the answers answers for your questions:
Are you seeing negative response times for all of the transactions?
> No, not all the transcations have the negative response times. Most of them have the positive values.
Are you seeing this issue in data produced by all three instances of packetbeat?
> Yes, I see the issues in all three instances.
Are there any issues with the system's clock? Can you check /var/log/messages for issues related to ntpd/time/clock?
> We are using the ntpd, I don't see the issues in the log  /var/log/messages.
The is the ntpd we use.
[root@ip-10-0-111-21 ~]# ntpd --version
ntpd 4.2.6p5
ntpd 4.2.6p5@1.2349-o Fri Dec 19 21:46:55 UTC 2014 (1)

I really appreciate your help, feel free to let me know if you need more.

**Comment by augustin149** [comment]
@ruflin I generate the pcap file, it appears I can upload the images here. Please let me know your mail address.

**Comment by ruflin** [comment]
@augustin149 My email is my gitname @elastic.co

**Comment by augustin149** [comment]
@ruflin pcap file has been sent to ruflin@elastic.co

**Comment by ruflin** [comment]
@augustin149 Thanks, email arrive. I will have a closer look. I updated the comment to not have the email address inside.

**Comment by ruflin** [comment]
@augustin149 We think we managed to solve the issue through #231 and also added some tests. I will close the issue. In case the issue persist, please reopen the issue.

Thanks a lot for helping us to solve the issue. The pcap files were really helpful.

**Comment by augustin149** [comment]
@ruflin Thank you, please let me know if you release a new version that fixes this issue.

**Comment by ruflin** [comment]
@augustin149 Will do.
