### ISSUE TITLE
Alternate protocols

### ISSUE THREAD

**Issue by johntdyer** [elastic/packetbeat#22]
This project looks super interesting.  I am curious though, do you support alternate protocols?  We would be super interested in sip and RTP for example

**Comment by jgrumboe** [comment]
At our company we would need Oracle indeed.
But really outstanding would be Corba as supported protocol since we found nothing right now to measure performance of Corba calls so far!
Would be cool to find some guideline how new protocols are implemented, so we could also help.

**Comment by elvarb** [comment]
Any updates on plans for new protocols?

**Comment by packetbeat** [comment]
Hi, for proprietary protocols like Oracle or MSSQL we are looking for interested partners to develop them together, because they are typically poorly specified and for the reverse engineering efforts we need traces from live installations. If you are interested in helping, drop us an email at info@packetbeat.com.

**Comment by jamroks** [comment]
Hi,

 In The concept of protocol as you define it, does it apply to Java for
instance to monitors The JVM that keep my application running . There is
some commercial product that does that like appdynamics and newrelic that
let you déploy an "agent" on the Target host and then when you start your
app you just need to pass the location of the javaagent :
-Djavaagent:/home/Russel/javaagent.jar  in the start up script of the app.
This give you very fine grained method acces Level and eventualy sql query
level monitoring.

Is it something that can be implemented In the future ? or maybe it' really
the scope of packetbeat wich has a différent approach ( only based on
network sniffing) ?

**Comment by jamroks** [comment]
Is it something that can be implemented In the future ? or maybe it' really
NOT the scope of packetbeat wich has a différent approach ( only based on
network sniffing) ?

**Comment by ciroiriarte** [comment]
Here's a good starting point for Oracle:
http://www.pythian.com/blog/repost-oracle-protocol/

Code from FreeTDS could help as starting point for MSSQL.

My 2 cents...

Regards,
CI.-

**Comment by packetbeat** [comment]
@jamroks Actually that is something we want to extend Packetbeat to. Hopefully also with the help of the community. Watch out for a blog post in the next couple of weeks.

@ciroiriarte Thanks for the links, we'll have a look.

**Comment by jamroks** [comment]
Thanks for the answer, that is great to know you'll be supporting this.  i'll
be eagerly waiting for your blog post and willing to Help this effort in
any way, for this killing feature

cheers

**Comment by elvarb** [comment]
Welcome to Elastic Packetbeat :)

Are there any changes to your plans for MSSQL and Oracle support?

**Comment by tsg** [comment]
@elvarb Thanks! What we can say at the moment is that MSSQL will come before Oracle, but probably not in the next 2-3 months. That changes if anyone in the community starts working on one of these. We'd gladly help in that case and probably make it earlier.

**Comment by tsg** [comment]
Split this one in individual tickets. Feel free to add comments to the individual tickets.

**Comment by andone87** [comment]
Hi, any chance for add ingres DB ?

**Comment by spacewander** [comment]
Is there any plan to support a pure HTTP/HTTPS output protocol? I'm working on a fork to add http/https Outputer currently.
BTW, will there be a group of API for people to implement their own output plugins?

**Comment by urso** [comment]
This issue is about protocol analyzers enhancement requests in packetbeat, not output plugins. Ticket is closed long time ago in favour of [separate enhancements requests](https://github.com/elastic/beats/issues?q=is%3Aopen+is%3Aissue+label%3A%22new+module%22+label%3APacketbeat).

No generic HTTP output plugin planned. No idea what's meant by API. Please open another discussion (best on discuss.elastic.co) to ask about API instead of hijacking old unrelated ticket.
