### ISSUE TITLE
The logging section is not documented

### ISSUE THREAD

**Issue by tsg** [elastic/packetbeat#229]
The `logging` section allows to configure Packetbeat's own messages, for example the following section sends the logs to rotating files:

<pre>
logging:
  to_files: true
  files:
    path: /tmp/packetbeat
    name: packetbeat
</pre>

Unfortunately these settings are currently not documented.

**Comment by ruflin** [comment]
Should we add this part of documentation to libbeat and reference it from the different beats?

**Comment by monicasarbu** [comment]
@ruflin Yes, that's the way to go.
