### ISSUE TITLE
Packetbeat windows client_location support

### ISSUE THREAD

**Issue by dayreiner** [elastic/packetbeat#268]
Not sure if this should be here or under libbeat, but the windows agent package doesn't seem to be able to locate the GeoIP database if its present on the system:

*geolite.go:52: WARN Couldn't load GeoIP database*

A quick peek in geolite.go shows a couple of linux filesystem locations for GeoIP.dat listed. I'm guessing if it's not in either of those locations it won't find it. Perhaps adding a windows-compatible path to the list is all that's needed.

Unless I'm missing some way to specify the database location for the Windows agent? Or is the client_location field not supported under windows?

**Comment by andrewkroh** [comment]
In the packetbeat.yml file you can specify the location of the [GeoLite City database file](http://geolite.maxmind.com/download/geoip/database/GeoLiteCity.dat.gz) using the configuration shown below.

```
shipper:
 geoip:
   paths:
     - 'C:\path\to\GeoIP.dat
```
We should update the documentation with this or include this option in the default packetbeat.yml file.

**Comment by dayreiner** [comment]
Thanks for pointing that out, that did the trick. Definitely one for the docs. Cheers.

**Comment by andrewkroh** [comment]
https://github.com/elastic/libbeat/issues/100
