### ISSUE TITLE
Updating the Packetbeat documentation

### ISSUE THREAD

**Issue by tarunsapra** [elastic/packetbeat#282]
In the overview page of Packetbeats there is no information of the fact that Packetbeats now supports DNS, thus would be nice if documentation can be updated. 

https://www.elastic.co/guide/en/beats/packetbeat/current/_overview.html

**Comment by andrewkroh** [comment]
Duplicate #269.

**Comment by monicasarbu** [comment]
@tarunsapra Indeed, the DNS is not added to the list of supported protocols for the beta3 version. We updated it only to the master: https://www.elastic.co/guide/en/beats/packetbeat/master/_overview.html. I will add it to beta3 as well. Thanks for noticing it.

**Comment by monicasarbu** [comment]
I added DNS to the list of supported protocols in the Overview page, but we need to add the configuration options for DNS under the configuration section (for beta3 and master).

**Comment by tarunsapra** [comment]
Thanks @monicasarbu

**Comment by monicasarbu** [comment]
This is fixed by https://github.com/elastic/packetbeat/pull/313.
