### ISSUE TITLE
Set default interface to en0 or lo0

### ISSUE THREAD

**Issue by ruflin** [elastic/packetbeat#291]
The `any` interface does not exist on Mac OS X. Currently in the config the any interface is set as default: https://github.com/elastic/packetbeat/blob/master/etc/packetbeat.yml#L34 As lot of engineers try packetbeat on their Mac OS X machine the default config doesn't work. We should change the default config to either en0 or lo0. I suggest to set it to lo0 as this will always exist. To still make testing without a config file as easy as possible, @urso suggests to add the interface as command line flag.

Issue for multiple interfaces can be found here: https://github.com/elastic/packetbeat/issues/263

**Comment by tsg** [comment]
The .tgz from the [download](https://www.elastic.co/downloads/beats/packetbeat) page already sniffs on `en0`. The magic is done in the [install_cfg](https://github.com/elastic/packetbeat/blob/master/Makefile#L37) target from the makefile.

**Comment by ruflin** [comment]
@tsg Interesting, wasn't aware of that. It solves the problem for all users that download the binary and run it. Instead of having to solve this during deployment, should we perhaps have it as part of the code? What happens when the config is left out? My suggestion is that it figures out which platform it is on an does the above. Like this we can even disable the devices by default ... Your thoughts?
