### ISSUE TITLE
packetbeat RPM replaces existing packetbeat.yml configuration

### ISSUE THREAD

**Issue by portante** [elastic/packetbeat#334]
When upgrading from -beta2 and -beta3 to -beta4 I lost all of my /etc/packetbeat/packetbeat.yml config files.  It looks like the .spec file in the tree has not been updated since -beta2, but it has the %config file marker.  Seems like a new .spec file was used to build the RPM which might have the problem.

See: http://www-uxsup.csx.cam.ac.uk/~jw35/docs/rpm_config.html

**Comment by vkhatri** [comment]
Considering the `sysv` model where we have `/etc/sysconfig/FILE` file which helps in preserving the changes, but it is not applicable to `packetbeat` as it has only a single yml file which makes it difficult to keep the changes.

Now, that i am think about it (apologies for the PR, should have been outcome of this issue), it might be a good idea to overwrite the file. But on the other hand for folks who does not have `chef/puppet/etc.`, it could be quite a challenge. 

IMHO, preserving the file seems like a good choice. But, i do not know all implications and back ground of not over writing the configuration file.

**Comment by andrewkroh** [comment]
Thanks once again, @portante. Yes, looking at how the RPM is generated, it is missing `%config`. Also `vendor` is not being set. I will fix these up this week and also see about signing the packages and generating a yum repo.

**Comment by tsg** [comment]
Apologies for the inconvenience :-(.

Indeed we changed the packaging to use fpm  and I missed using the `--config-files` option. @andrewkroh, if you get to it, [this](https://github.com/elastic/beats-packer/blob/master/platforms/centos/run.sh.j2#L11) is where we call fpm. Please also check the debs for the same issue.

**Comment by andrewkroh** [comment]
I opened a PR (#338) to remove the old RPM spec from this repository. I also opened elastic/beats-packer#17 to mark the yml file as a config file within the RPM.
