### ISSUE TITLE
-d "*" does not include the "publish" selector

### ISSUE THREAD

**Issue by darxriggs** [elastic/packetbeat#339]
When running `./packetbeat -e -c etc/packetbeat.yml -d "*"` no output from publisher is logged.

When running `./packetbeat -e -c etc/packetbeat.yml -d "*,publish"` the output from publisher is logged.

I would expect that `-d "*"` enables debug logging for publisher.

**Comment by urso** [comment]
the '*' option should work as it sets a bool being checked before any selectors. Can you provide some console output for comparison?

**Comment by andrewkroh** [comment]
I think the cause is that `logp.IsDebug` doesn't handle `*` correctly.

https://github.com/elastic/libbeat/blob/master/publisher/preprocess.go#L61

**Comment by urso** [comment]
@andrewkroh you are right. And it's not the only selector being affected.

**Comment by tsg** [comment]
Fixed by elastic/libbeat#226.
