### ISSUE TITLE
Travis-ci does not recognize Build Status link

### ISSUE THREAD

**Issue by wilsonmar** [elastic/packetbeat#360]
"The repository at packetbeat/packetbeat was not found."
is shown when
in the README.md under https://github.com/elastic/packetbeat/tree/master/tests 
when I click on “Build Status” link
https://travis-ci.org/packetbeat/packetbeat

**Comment by ruflin** [comment]
@wilsonmar The link here is definitively outdated and should be updated. Thanks for reporting this.
