### ISSUE TITLE
URL in packetbeat.yml not found

### ISSUE THREAD

**Issue by wilsonmar** [elastic/packetbeat#361]
After downloading packetbeat-1.0.0-rc1-darwin.gz
I open packetbeat.yml. The URL mentioned on line 4
https://www.elastic.co/guide/en/beats/packetbeat/current/configuration.html
results in a 404 error page.

**Comment by urso** [comment]
thanks for reporting.

Correct link is: https://www.elastic.co/guide/en/beats/packetbeat/current/packetbeat-configuration.html
