### ISSUE TITLE
panic: runtime error: index out of range

### ISSUE THREAD

**Issue by kbering** [elastic/packetbeat#369]
When running packetbeat (1.0.0-rc1) on windows 7 I get this quite long error after a short while:

[packetbeat.yml.txt](https://github.com/elastic/packetbeat/files/33835/packetbeat.yml.txt)

goroutine 41 [running]:
github.com/elastic/packetbeat/protos/dns.(*Dns).publishTransaction(0x20fb49f0, 0
x20fe04b0)
        /go/src/github.com/elastic/packetbeat/protos/dns/dns.go:427 +0xe5a
github.com/elastic/packetbeat/protos/dns.(*Dns).expireTransaction(0x20fb49f0, 0x
20fe04b0)
        /go/src/github.com/elastic/packetbeat/protos/dns/dns.go:453 +0x13c
github.com/elastic/packetbeat/protos/dns.(*Dns).Init.func1(0x78e4c0, 0x210dca50,
 0x769980, 0x20fe04b0)
        /go/src/github.com/elastic/packetbeat/protos/dns/dns.go:302 +0x66
github.com/elastic/libbeat/common.(*Cache).CleanUp(0x20ff4f60, 0x0)
        /go/src/github.com/elastic/packetbeat/Godeps/_workspace/src/github.com/e
lastic/libbeat/common/cache.go:184 +0x210
github.com/elastic/libbeat/common.(*Cache).StartJanitor.func1(0x20ff4f90, 0x20ff
4f60)
        /go/src/github.com/elastic/packetbeat/Godeps/_workspace/src/github.com/e
lastic/libbeat/common/cache.go:221 +0x8f
created by github.com/elastic/libbeat/common.(*Cache).StartJanitor
        /go/src/github.com/elastic/packetbeat/Godeps/_workspace/src/github.com/e
lastic/libbeat/common/cache.go:227 +0x8f

goroutine 1 [chan receive, 45 minutes]:
main.(*Packetbeat).Run(0x201a8000, 0x20fb4a20, 0x0, 0x0)
        /go/src/github.com/elastic/packetbeat/packetbeat.go:227 +0xa3
github.com/elastic/libbeat/beat.(*Beat).Run(0x20fb4a20)
        /go/src/github.com/elastic/packetbeat/Godeps/_workspace/src/github.com/e
lastic/libbeat/beat/beat.go:130 +0x1a4
main.main()
        /go/src/github.com/elastic/packetbeat/main.go:40 +0x2e0

goroutine 17 [syscall, 45 minutes, locked to thread]:
runtime.goexit()
        /usr/local/go/src/runtime/asm_386.s:1662 +0x1

goroutine 5 [syscall, 45 minutes]:
os/signal.loop()
        /usr/local/go/src/os/signal/signal_unix.go:22 +0x1a
created by os/signal.init.1
        /usr/local/go/src/os/signal/signal_unix.go:28 +0x36

goroutine 13 [select, 45 minutes]:
golang.org/x/sys/windows/svc/debug.Run.func1(0x2015ae40, 0x2015adc0, 0x2015ae00)

        /go/src/golang.org/x/sys/windows/svc/debug/service.go:32 +0x14c
created by golang.org/x/sys/windows/svc/debug.Run
        /go/src/golang.org/x/sys/windows/svc/debug/service.go:38 +0xd2

goroutine 11 [IO wait]:
net.runtime_pollWait(0x10673e8, 0x72, 0x20f4d5c0)
        /usr/local/go/src/runtime/netpoll.go:157 +0x55
net.(*pollDesc).Wait(0x205e2530, 0x72, 0x0, 0x0)
        /usr/local/go/src/net/fd_poll_runtime.go:73 +0x35
net.(*ioSrv).ExecIO(0x20faec90, 0x205e2498, 0x85e2f8, 0x7, 0x949550, 0x5b1560ab,
 0x0, 0x0)
        /usr/local/go/src/net/fd_windows.go:182 +0x122
net.(*netFD).Read(0x205e2460, 0x20fe2000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/fd_windows.go:463 +0x129
net.(*conn).Read(0x20faeca0, 0x20fe2000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/net.go:172 +0xb9
net/http.noteEOFReader.Read(0x1067460, 0x20faeca0, 0x20207acc, 0x20fe2000, 0x100
0, 0x1000, 0x205da0e0, 0x0, 0x0)
        /usr/local/go/src/net/http/transport.go:1370 +0x55
net/http.(*noteEOFReader).Read(0x20fc5030, 0x20fe2000, 0x1000, 0x1000, 0x1, 0x0,
 0x0)
        <autogenerated>:126 +0xae
bufio.(*Reader).fill(0x20fb5a10)
        /usr/local/go/src/bufio/bufio.go:97 +0x172
bufio.(*Reader).Peek(0x20fb5a10, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/bufio/bufio.go:132 +0xad
net/http.(*persistConn).readLoop(0x20207aa0)
        /usr/local/go/src/net/http/transport.go:876 +0xe3
created by net/http.(*Transport).dialConn
        /usr/local/go/src/net/http/transport.go:685 +0xabc

goroutine 12 [select]:
net/http.(*persistConn).writeLoop(0x20207aa0)
        /usr/local/go/src/net/http/transport.go:1009 +0x303
created by net/http.(*Transport).dialConn
        /usr/local/go/src/net/http/transport.go:686 +0xadc

goroutine 34 [select]:
github.com/elastic/libbeat/publisher.(*messageWorker).run(0x20ff20b0)
        /go/src/github.com/elastic/packetbeat/Godeps/_workspace/src/github.com/e
lastic/libbeat/publisher/worker.go:53 +0x1c4
created by github.com/elastic/libbeat/publisher.(*messageWorker).init
        /go/src/github.com/elastic/packetbeat/Godeps/_workspace/src/github.com/e
lastic/libbeat/publisher/worker.go:47 +0xc5

goroutine 35 [select]:
github.com/elastic/libbeat/publisher.(*bulkWorker).run(0x20ff40c0)
        /go/src/github.com/elastic/packetbeat/Godeps/_workspace/src/github.com/e
lastic/libbeat/publisher/bulk.go:50 +0x3eb
created by github.com/elastic/libbeat/publisher.newBulkWorker
        /go/src/github.com/elastic/packetbeat/Godeps/_workspace/src/github.com/e
lastic/libbeat/publisher/bulk.go:38 +0x18b

goroutine 36 [select]:
github.com/elastic/libbeat/publisher.(*messageWorker).run(0x20b64340)
        /go/src/github.com/elastic/packetbeat/Godeps/_workspace/src/github.com/e
lastic/libbeat/publisher/worker.go:53 +0x1c4
created by github.com/elastic/libbeat/publisher.(*messageWorker).init
        /go/src/github.com/elastic/packetbeat/Godeps/_workspace/src/github.com/e
lastic/libbeat/publisher/worker.go:47 +0xc5

goroutine 37 [select, 45 minutes]:
github.com/elastic/libbeat/publisher.(*messageWorker).run(0x20fe4500)
        /go/src/github.com/elastic/packetbeat/Godeps/_workspace/src/github.com/e
lastic/libbeat/publisher/worker.go:53 +0x1c4
created by github.com/elastic/libbeat/publisher.(*messageWorker).init
        /go/src/github.com/elastic/packetbeat/Godeps/_workspace/src/github.com/e
lastic/libbeat/publisher/worker.go:47 +0xc5

goroutine 38 [select]:
github.com/elastic/libbeat/common.(*Cache).StartJanitor.func1(0x20ff4ed0, 0x20ff
4ea0)
        /go/src/github.com/elastic/packetbeat/Godeps/_workspace/src/github.com/e
lastic/libbeat/common/cache.go:219 +0xd3
created by github.com/elastic/libbeat/common.(*Cache).StartJanitor
        /go/src/github.com/elastic/packetbeat/Godeps/_workspace/src/github.com/e
lastic/libbeat/common/cache.go:227 +0x8f

goroutine 39 [chan receive, 45 minutes]:
github.com/elastic/packetbeat/protos/thrift.(*Thrift).publishTransactions(0x2015
a3c0)
        /go/src/github.com/elastic/packetbeat/protos/thrift/thrift.go:1075 +0x8e

created by github.com/elastic/packetbeat/protos/thrift.(*Thrift).Init
        /go/src/github.com/elastic/packetbeat/protos/thrift/thrift.go:263 +0x255

goroutine 40 [select]:
github.com/elastic/libbeat/common.(*Cache).StartJanitor.func1(0x20ff4f30, 0x20ff
4f00)
        /go/src/github.com/elastic/packetbeat/Godeps/_workspace/src/github.com/e
lastic/libbeat/common/cache.go:219 +0xd3
created by github.com/elastic/libbeat/common.(*Cache).StartJanitor
        /go/src/github.com/elastic/packetbeat/Godeps/_workspace/src/github.com/e
lastic/libbeat/common/cache.go:227 +0x8f

goroutine 42 [select]:
github.com/elastic/libbeat/common.(*Cache).StartJanitor.func1(0x20ff4ff0, 0x20ff
4fc0)
        /go/src/github.com/elastic/packetbeat/Godeps/_workspace/src/github.com/e
lastic/libbeat/common/cache.go:219 +0xd3
created by github.com/elastic/libbeat/common.(*Cache).StartJanitor
        /go/src/github.com/elastic/packetbeat/Godeps/_workspace/src/github.com/e
lastic/libbeat/common/cache.go:227 +0x8f

goroutine 43 [select]:
github.com/elastic/libbeat/common.(*Cache).StartJanitor.func1(0x20ff5050, 0x20ff
5020)
        /go/src/github.com/elastic/packetbeat/Godeps/_workspace/src/github.com/e
lastic/libbeat/common/cache.go:219 +0xd3
created by github.com/elastic/libbeat/common.(*Cache).StartJanitor
        /go/src/github.com/elastic/packetbeat/Godeps/_workspace/src/github.com/e
lastic/libbeat/common/cache.go:227 +0x8f

goroutine 44 [select]:
github.com/elastic/libbeat/common.(*Cache).StartJanitor.func1(0x20ff50b0, 0x20ff
5080)
        /go/src/github.com/elastic/packetbeat/Godeps/_workspace/src/github.com/e
lastic/libbeat/common/cache.go:219 +0xd3
created by github.com/elastic/libbeat/common.(*Cache).StartJanitor
        /go/src/github.com/elastic/packetbeat/Godeps/_workspace/src/github.com/e
lastic/libbeat/common/cache.go:227 +0x8f

goroutine 45 [select]:
github.com/elastic/libbeat/common.(*Cache).StartJanitor.func1(0x20ff5110, 0x20ff
50e0)
        /go/src/github.com/elastic/packetbeat/Godeps/_workspace/src/github.com/e
lastic/libbeat/common/cache.go:219 +0xd3
created by github.com/elastic/libbeat/common.(*Cache).StartJanitor
        /go/src/github.com/elastic/packetbeat/Godeps/_workspace/src/github.com/e
lastic/libbeat/common/cache.go:227 +0x8f

goroutine 46 [select]:
github.com/elastic/libbeat/common.(*Cache).StartJanitor.func1(0x20ff51a0, 0x20ff
5170)
        /go/src/github.com/elastic/packetbeat/Godeps/_workspace/src/github.com/e
lastic/libbeat/common/cache.go:219 +0xd3
created by github.com/elastic/libbeat/common.(*Cache).StartJanitor
        /go/src/github.com/elastic/packetbeat/Godeps/_workspace/src/github.com/e
lastic/libbeat/common/cache.go:227 +0x8f

goroutine 47 [chan receive, 45 minutes]:
github.com/elastic/libbeat/service.HandleSignals.func1(0x20b64dc0, 0x20fe7ea0)
        /go/src/github.com/elastic/packetbeat/Godeps/_workspace/src/github.com/e
lastic/libbeat/service/service.go:23 +0x31
created by github.com/elastic/libbeat/service.HandleSignals
        /go/src/github.com/elastic/packetbeat/Godeps/_workspace/src/github.com/e
lastic/libbeat/service/service.go:26 +0x170

goroutine 48 [chan receive, 45 minutes]:
github.com/elastic/libbeat/service.(*beatService).Execute(0xdfd954, 0x20faecd8,
0x1, 0x1, 0x2015adc0, 0x2015ae00, 0x405800, 0x0)
        /go/src/github.com/elastic/packetbeat/Godeps/_workspace/src/github.com/e
lastic/libbeat/service/service_windows.go:21 +0xdd
golang.org/x/sys/windows/svc/debug.Run(0x20155a00, 0xe, 0x1067528, 0xdfd954, 0x0
, 0x0)
        /go/src/golang.org/x/sys/windows/svc/debug/service.go:40 +0x14d
github.com/elastic/libbeat/service.ProcessWindowsControlEvents(0x20ff6518)
        /go/src/github.com/elastic/packetbeat/Godeps/_workspace/src/github.com/e
lastic/libbeat/service/service_windows.go:55 +0x209
created by github.com/elastic/libbeat/service.HandleSignals
        /go/src/github.com/elastic/packetbeat/Godeps/_workspace/src/github.com/e
lastic/libbeat/service/service.go:32 +0x1b4

goroutine 49 [syscall, locked to thread]:
github.com/tsg/gopacket/pcap._Cfunc_pcap_next_ex(0x1985cc0, 0x20fe56f8, 0x20fe56
fc, 0x0)
        ??:0 +0x37
github.com/tsg/gopacket/pcap.(*Handle).getNextBufPtrLocked(0x20fe56e0, 0x20185eb
8, 0x0, 0x0)
        /go/src/github.com/elastic/packetbeat/Godeps/_workspace/src/github.com/t
sg/gopacket/pcap/pcap.go:314 +0x59
github.com/tsg/gopacket/pcap.(*Handle).ReadPacketData(0x20fe56e0, 0x0, 0x0, 0x0,
 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /go/src/github.com/elastic/packetbeat/Godeps/_workspace/src/github.com/t
sg/gopacket/pcap/pcap.go:271 +0x97
github.com/elastic/packetbeat/sniffer.(*SnifferSetup).Run(0x20ff4e70, 0x0, 0x0)
        /go/src/github.com/elastic/packetbeat/sniffer/sniffer.go:290 +0x1b7
main.(*Packetbeat).Run.func1(0x201a8000)
        /go/src/github.com/elastic/packetbeat/packetbeat.go:212 +0x35
created by main.(*Packetbeat).Run
        /go/src/github.com/elastic/packetbeat/packetbeat.go:218 +0x40

**Comment by andrewkroh** [comment]
I think you may have captured a DNS query that contained no questions. It would be helpful to have a copy of the packet that caused this crash. Would it be possible to run packetbeat with the `-dump some/dir/captured-data.pcap` command line option and send me the capture? If so, you can email it to me at andrew dot kroh at elastic dot co.

Line that it crashed on:
https://github.com/elastic/packetbeat/blob/master/protos/dns/dns.go#L427

**Comment by andrewkroh** [comment]
For reference, this is the odd packet that caused the crash. It is odd to me because it is essentially all zeros.

![screen shot 2015-11-16 at 3 57 22 pm](https://cloud.githubusercontent.com/assets/4565752/11195607/b7ed1c72-8c80-11e5-8547-500ff0711a7e.png)

This issue should be fixed now and will be released in RC2.
