### ISSUE TITLE
Redis monitoring error

### ISSUE THREAD

**Issue by devdesco-ceo** [elastic/packetbeat#387]
Nov 19 18:07:01 gateway2 /usr/bin/packetbeat[2639]: log.go:113: ParseRedis exception. Recovering, but please report this: runtime error: invalid memory address or nil pointer dereference.
Nov 19 18:07:01 gateway2 /usr/bin/packetbeat[2639]: log.go:114: Stacktrace: /go/src/github.com/elastic/packetbeat/Godeps/_workspace/src/github.com/elastic/libbeat/logp/log.go:114 (0x48c3f6)#012/usr/local/go/src/runtime/asm_amd64.s:437
 (0x47d72e)#012/usr/local/go/src/runtime/panic.go:423 (0x44d329)#012/usr/local/go/src/runtime/panic.go:42 (0x44b9e9)#012/usr/local/go/src/runtime/sigpanic_unix.go:24 (0x46228a)#012/go/src/github.com/elastic/packetbeat/protos/redis/red
is.go:579 (0x51b4c2)#012/go/src/github.com/elastic/packetbeat/protos/tcp/tcp.go:87 (0x520853)#012/go/src/github.com/elastic/packetbeat/protos/tcp/tcp.go:173 (0x52198d)#012/go/src/github.com/elastic/packetbeat/decoder/decoder.go:136 (0
x6c7401)#012/go/src/github.com/elastic/packetbeat/sniffer/sniffer.go:352 (0x532f69)#012/go/src/github.com/elastic/packetbeat/packetbeat.go:212 (0x422f2b)#012/usr/local/go/src/runtime/asm_amd64.s:1696 (0x47fa71)

**Comment by andrewkroh** [comment]
This looks to be the same issue as #384. So I am going to close this one as a duplicate.
