### ISSUE TITLE
More protocols please!!!

### ISSUE THREAD

**Issue by devdesco-ceo** [elastic/packetbeat#388]
Would like to sniff/monitor traffic on these protocols...

  smtp:
    ports: [25]

  smtps:
    ports: [465, 587]

  pop3s:
    ports: [995]

  imaps:
    ports: [993]

  ssh:
    ports: [22, 2022]

  ftp:
    ports: [21]

**Comment by ruflin** [comment]
@devdesco-ceo There is already a list of requested protocols which you can find here: https://github.com/elastic/packetbeat/labels/new%20protocol Some of the above protocols are already in the list, some are not. Feel free to open a separate issue for each missing protocol as it makes it easier to track progress.

As adding a new protocol is a big chunk of work we can't add all the protocols ourself and must prioritise. We are always happy to take contributions from the community. So in case you feel comfortable adding one of the protocols yourself, feel free to open a PR.

**Comment by tsg** [comment]
In addition, we will add the possibility to monitor at TCP/UDP level also the protocols we don't understand from an application point of view, see #373.

I'm closing this one as the format is not efficient for tracking. If there's any protocol you want that we don't yet have a ticket for, please open one.
