### ISSUE TITLE
https protocol Support

### ISSUE THREAD

**Issue by kpcool** [elastic/packetbeat#406]
With Packbeats, I am trying to monitor the https requests made on our system, but these requests are not getting monitored on Packetbeats. 

I am able to monitor http, mysql traffic, so I am pretty confident that my setup is fine. 

Is there something that I need to do to enable https packetbeats monitoring?

**Comment by urso** [comment]
well, packetbeat is a passive service working on raw network packets and can therefore not deal well with encryption. Normally you want to deploy it behind some SSL endpoint.

Possibly related: #48, #373

**Comment by monicasarbu** [comment]
@kpcool Currently Packetbeat is not able to decrypt the network traffic, but we are planning for the next release to display some data that can be easily extracted from the encrypted network traffic. Please see #373.

**Comment by monicasarbu** [comment]
Closing this issue as it duplicates #48
