### ISSUE TITLE
multiple indices for filebeat and packetbeat

### ISSUE THREAD

**Issue by congpine** [elastic/packetbeat#407]
Hi, 
I'm gonna use filebeat as well as packetbeat on my servers to ship logs to logstash/redis/elasticsearch and viewable in Kibana.
I can see there is an option to configure index name in Filebeat and Packetbeat.
By default, they are: filebeat and packetbeat. 
Should I create a separate index name for each tool, or should I send them all to 1 common index ?

**Comment by ruflin** [comment]
@congpine As these are two completely different data sets I would highly recommend to send them to two different indices. It will give you much more flexibility in the long run.

**Comment by congpine** [comment]
thanks for your quick response. @ruflin 
My next issue is: how can I separate them from the Logstash Indexer if my setup is: 
filebeat/packetbeat => Logstash (to capture logs) => Redis => Logstash Indexer => ElasticSearch.

I have tried to configure it but they all went to logstash index.
on packetbeat.yml , I have: 
```
logstash
   index : packetbeat
```
on Logstash (capture):
```
input {
  beats {
    port => 5044
    type => "logs_from_beat"
  }
}

output {
  redis {
        host => "x.x.x.x:6379"
        data_type => "list"
        key => "packetbeat"
}
}
```
I can see logs sent to Redis Queue with key: **packetbeat**
on Logstash Indexer, I have: 
```
input {
  redis {
    host => "10.8.105.51"
    port => "6379"
    data_type => "list"
    key => "logstash"
    codec => json
  }
  redis {
    host => "10.8.105.51"
    port => "6379"
    data_type => "list"
    key => "packetbeat"
    codec => json
  }
  tcp {
        port => 5001
        type => syslogjson
        codec => json
  }
}
output {
  elasticsearch { 
  }
}
```
But all logs end-up inside index name: logstash. 

What am I missing ?

**Comment by ruflin** [comment]
Why don't you send the packetbeat data directly to elasticsearch?

**Comment by ruflin** [comment]
@congpine It would be better to have this discussion here (https://discuss.elastic.co/c/beats) as we try to keep the Github issues for bugs, enhancements etc. Do you mind to continue the discussion there?

**Comment by congpine** [comment]
sorry about that. I will close this and go to the Forum for discussion.

**Comment by urso** [comment]
@congpine check you elasticsearch output configuration. Try to [configure you elasticsearch index](https://www.elastic.co/guide/en/logstash/current/plugins-outputs-elasticsearch.html#plugins-outputs-elasticsearch-index). It defaults to logstash index.

**Comment by ruflin** [comment]
@congpine Thanks.

**Comment by congpine** [comment]
I have created the discussion here, please let me know your opinion. Thanks

https://discuss.elastic.co/t/what-is-the-best-setup-for-beats-and-elk-stack/35827
