### ISSUE TITLE
[Enhancement] Integration with Zabbix

### ISSUE THREAD

**Issue by dvwyngaa** [elastic/packetbeat#57]
Hi,

Are there any plans to integrate PacketBeat with Zabbix (http://www.zabbix.com)? Thus sending events like high response times to Zabbix, which in turn will send alerts to the relevant support staff?

Or putting in another way, will PacketBeat get a API in future? Or does it have one now?

Regards,

Dawid

**Comment by tsg** [comment]
Closing this one as not really related to Packetbeat itself.
