### ISSUE TITLE
packetbeat agent get so much of Wrong length  messages and cpu usage is high

### ISSUE THREAD

**Issue by mk-qi** [elastic/packetbeat#62]
Sep  3 15:23:04 redis67 /usr/bin/packetbeat[14881]: redis.go:295: Wrong length of data: 1376 instead of 1480
Sep  3 15:23:04 redis67 /usr/bin/packetbeat[14881]: redis.go:295: Wrong length of data: 1376 instead of 1536
Sep  3 15:23:04 redis67 /usr/bin/packetbeat[14881]: redis.go:254: Failed to read number of bulk messages: strconv.ParseInt: parsing "2*4": invalid syntax
Sep  3 15:23:04 redis67 /usr/bin/packetbeat[14881]: redis.go:295: Wrong length of data: 46 instead of 43
Sep  3 15:23:04 redis67 /usr/bin/packetbeat[14881]: redis.go:295: Wrong length of data: 1376 instead of 1582
Sep  3 15:23:04 redis67 /usr/bin/packetbeat[14881]: redis.go:295: Wrong length of data: 1376 instead of 
Sep  3 15:23:05 redis67 /usr/bin/packetbeat[14881]: redis.go:281: Failed to read bulk message: strconv.ParseInt: parsing "39*24": invalid syntax

the protocol parser error(response message is wrong)
---------------------------------
redis.request		INCR goshop:tracking:ticket:step_id
redis.response		HSETNX goshop:tracking:ticket:995585455:info ctime 1409729334
request_raw		INCR goshop:tracking:ticket:step_id
response_raw		HSETNX goshop:tracking:ticket:995585455:info ctime 1409729334

cpu is high (top output)
---------------------------------
14881 root      20   0  233m  12m 7460 S 103.7  0.0   2:28.34 packetbeat

**Comment by tsg** [comment]
Closing this one because we don't support the particular use case.
