### ISSUE TITLE
Keepalive Connections

### ISSUE THREAD

**Issue by wojons** [elastic/packetbeat#64]
I am noticing that some a small percent lets say 5% of my request times look really slow. when i look at the request i see the headers and body of 10 or more requests and then finally the response from one of them. I am using cloudflare and I am sure its using keep alive connections so is there a chance packetbeat is getting confused bye this and making it look like the connection is superlong

**Comment by tsg** [comment]
Closing this one because there's no clear thing to fix and there were quite a few code changes in the mean time. If you have new data about it, please reopen.
