### ISSUE TITLE
MongoDB agent

### ISSUE THREAD

**Issue by offlinehacker** [elastic/packetbeat#67]
Mongodb agent would be really awesome for nodejs apps :)

PS: Nice project!

**Comment by cphoover** [comment]
+1 upboat

**Comment by albanm** [comment]
+1

**Comment by efkan** [comment]
+1

**Comment by albanm** [comment]
For your information, I'm working on a pull request for this. It is almost ready, I hope to submit it in a few days.

**Comment by efkan** [comment]
I'm looking forward to hearing your development news!

**Comment by cphoover** [comment]
@albanm awesome!!

**Comment by monicasarbu** [comment]
MongoDB support was added in beta2.
