### ISSUE TITLE
Create a guide for adding a new protocol

### ISSUE THREAD

**Issue by szelok** [elastic/packetbeat#73]
Any guidelines if we want to add our own protocols/procs?

**Comment by socketubs** [comment]
I think the missing metrics for now are system metrics, like memory, disk, io, cpu, etc.
Is it something you have planned to add in a near future ?

**Comment by tsg** [comment]
Not in the near future, sorry, we're focusing on application metrics. You can use collectd + graphite or influxdb + graphana for system metrics, and you'll get a similar interface.

**Comment by andrewkroh** [comment]
A developer guide has been created: [Developer guide: adding a new protocol](https://www.elastic.co/guide/en/beats/packetbeat/current/_developer_guide_adding_a_new_protocol.html)
