### ISSUE TITLE
Implement packet decoding with gopacket

### ISSUE THREAD

**Issue by vrecan** [elastic/packetbeat#76]
It feels like this could be improved significantly by using [gopacket](http://godoc.org/code.google.com/p/gopacket) with pf_ring which would allow much higher packet rates and improved decoding of basic protocol types (tcp, udp) and easily be able to add ipv6 support.

**Comment by tsg** [comment]
Closing this one, as we do use gopacket now. Pull requests for improvements are always appreciated :-)
