### ISSUE TITLE
Will there be some sort of throttling or sample rate?

### ISSUE THREAD

**Issue by thomaslohner** [elastic/packetbeat#79]
First of all, this looks really cool and very promising.I guess storing every single http/redis/mysql transaction won't work very well for large sites. A million page impressions per day could result in tens or even hundreds of millions transactions per day which will probably kill elasticsearch's performance. Do you plan on addressing this issue?

**Comment by tsg** [comment]
Posted https://github.com/elastic/libbeat/issues/14.
