### ISSUE TITLE
RDS was question

### ISSUE THREAD

**Issue by epinault** [elastic/packetbeat#90]
Hi, 

So my understanding is that packbeat runs on the server usually (the listening port). Is there a way from the client to monitor the queries to postgres? 

Currently I use RDS and don't  have any way to run packet beat on the server. So I was wondering is from client software I could monitor the queries as well?

Thanks

**Comment by tsg** [comment]
You generally can sniff on the client side as well. All it matters is that the packetbeat agent captures the traffic. This can be on the server but also on the client.

**Comment by epinault** [comment]
I see. So I must be missing something then.  I have a small rails app that talks to postgres in RDS..  I believe my config file is correct (see below the protocols section). 

I was expecting to be able to run it on the web server and see the http traffic and postgres queries in the packet beat . But only see http traffic so far..

One thing is I setup to use the  file systemas output for the events (instead of elastic search) to see everything sent but did not see anything related to postgres. So far I can't seem to see anything. 

I am also using the latest 0.4.3.1 for debian on ubuntu 12.04. what else I am missing?

```
[output]
  [output.elasticsearch]
    # Comment this option if you don't want to output to Elasticsearch.
    #enabled = true

    # Set the host and port where to find Elasticsearch.
    host = "10.xxx.xxx.xxx"
    port = 9200

    # Comment this option if you don't want to store the topology in Elasticsearch.
    save_topology = true

  [output.file]
    enabled = true
    path="/tmp/packetbeat"
    filename="packetbeat"
    rotate_every_kb=1000
    number_of_files=7

[interfaces]
# Select on which network interfaces to sniff. You can use the "any"
# keyword to sniff on all connected interfaces.
device = "any"

[procs]
# Which processes to monitor and how to find them. The processes can
# be found by searching their command line by a given string.
  #[procs.monitored.mysqld]
  #cmdline_grep = "mysqld"

  [procs.monitored.pgsql]
  cmdline_grep = "postgres"

  [procs.monitored.nginx]
  cmdline_grep = "nginx"

  [procs.monitored.app]
  cmdline_grep = "gunicorn"
```

**Comment by tsg** [comment]
You seem to be missing the "protocols" part of the configuration. It should look something like this:

    [protocols]
      [protocols.http]
      ports = [80, 8080]

      [protocols.pgsql]
      ports = [5432]

The pgsql port should match the one that you use to connect to Postgres.

Are you using VPC for the connection to RDS?

**Comment by tsg** [comment]
Just to add to the above, to reduce the load, Packetbeat only captures the packets on the TCP ports that are configured under the protocols section. So you need that part (I'm kind of surprised you got HTTP traffic without it).

**Comment by epinault** [comment]
Yes, sorry, I forgot to copy the section of the protocols but it looks like what you just showed

I am not using VPC per say though default account nowadays use VPC

**Comment by tsg** [comment]
Ok, it could be that the postgres client uses encryption by default but you don't really need it because VPC also encrypts the traffic. The way I would check if that's the case is by installing `ngrep` and run something like this:

     ngrep -d any "" "port 5432"

If that's showing some clear text queries when they happen, then this is not the problem.

**Comment by epinault** [comment]
hum yea. looks unreadable. So that might be the problem .

This is an example:

```
0.187.41.211:5432 -> 10.169.38.176:56497 [AP]
  .... ..".P.Y.Q...../..n....aa.....<J6..... .`..m..T.v$n..i..g.._.R.rqMA].a|c../....W..C..Fx.1....w#..I.f<.._.I
  ..|.JN.$.B.V.....F:S2...#T...%...5..m.(..3.vJ@..9..u&.rWr..\.5. ...J.~...DqQ.GU...4.[.t7...t....._.<..Y.^..@w<
  ....J..ed......q..nh_...)..`Po..o7../.G}...o.....8...LxLy....;r..r.H.;.~1.. ..............Q....r#....6k.....5.
  .2.K...@(......<CW'>............P.\t....It....E..V.|.."6q..O.#v.U....-.y8VS....@_R..........e..Q.t.o0..$..y..e
  *UTW0.(...cR(k.......#.'.&rT.,.n.<X.M..x...}.(..B..eY..........b[CK&..F.~.u..q4...._.O..D._.<.../cL.Wo.._.....
  .v8..b..g%>.z.`........?...7o.f.r.H..??/....]..E.>].D^.B........(Ss.....:..Nr.Tc.`.....?..5....;.]..\F...[j1f.
  5...N?>>O...c.....4t..                                                                                        
##
```

**Comment by NeckBeardPrince** [comment]
*sigh* damn came here for the same thing and yup.. encrypted traffic.

**Comment by tsg** [comment]
Closing this issue as we prefer questions and discussions to go on the new [forums](https://discuss.elastic.co/c/beats/packetbeat).
