### ISSUE TITLE
Kibana 4?

### ISSUE THREAD

**Issue by discogestalt** [elastic/packetbeat#97]
Any chance you have, or are working on, dashboard configs for Kibana 4? I'm running (and need to stay on) Kibana 4 due to some of the new features that meet requirements I have for my org., and I'd much rather feed packetbeat data into my existing cluster than to have to set up a separate cluster just for this.

**Comment by tsg** [comment]
Yes, we'll be moving to Kibana4 with release 0.5.0 which we expect in a few days.

**Comment by discogestalt** [comment]
Awesome, I'm looking forward to it :+1:

**Comment by whisk3y** [comment]
Any news on the release date of 0.5.0?

**Comment by cphoover** [comment]
What's the status on this one??

**Comment by proffalken** [comment]
Dashboards were released for Kibana 4 by #108 - I'm in the process of playing with them now, however they appear to load OK.

**Comment by tsg** [comment]
Starting with 1.0.0.Beta1 Kibana 4 dashboards are the default.
